### ISSUE TITLE
[BUG] Copy button glides along when scrolling, it should remain fixed

### ISSUE THREAD

**Issue by Parikshit2001** [code100x/daily-code#106]
https://github.com/code100x/daily-code/assets/72187548/0788faa8-712b-4769-9f62-61fb41376c7f

**Comment by Programmer-Dost** [comment]
I think they are using predefined component form notion. Can't do much. I could be wrong but code component is being imported from notion.

**Comment by ashwin-athappan** [comment]
I am able to reach the code block. But the next task is to add a custom code snippet block.

![image](https://github.com/code100x/daily-code/assets/32098750/a34e7d1b-d175-40a0-8a34-567f9ef82129)

The code blocks are replaced by plain text.

**Comment by ashwin-athappan** [comment]
I think I have arrived at a solution.

![copy_bug_fix](https://github.com/code100x/daily-code/assets/32098750/c579caf6-59ac-4c3a-9468-f8bb20ba20ad)

Seems to work now.

**Comment by ashwin-athappan** [comment]
I will be working on this and I will raise a PR for this.
