### ISSUE TITLE
AppBar is not responsive for smaller screens

### ISSUE THREAD

**Issue by INVINCIalokk** [code100x/daily-code#108]
https://github.com/code100x/daily-code/blob/27f3f01acd01f3e65a09781de50f6400f387b502/packages/ui/src/BlogAppbar.tsx#L8

**Comment by prajjwal2-3** [comment]
Taking this up

**Comment by prajjwal2-3** [comment]
Working on it

**Comment by siddanth-6365** [comment]
Fix this also, the navbar need to get hide when I scroll down,currently it is sticky 
![Screenshot_20240408_143239_Chrome](https://github.com/code100x/daily-code/assets/114846048/5ed8019f-b289-412a-81e8-aa9e2dddb6a2)

**Comment by vatan45** [comment]
<img width="660" alt="Screens
<img width="547" alt="Screenshot 2024-04-08 at 11 50 32 PM" src="https://github.com/code100x/daily-code/assets/142028575/d4ec1f21-8ee2-4ae3-acb5-4003b2d6e746">
hot 2024-04-08 at 11 50 23 PM" src="https://github.com/code100x/daily-code/assets/142028575/95fcc20a-445f-4083-ab99-2396b6314c45">
done with this issue , raise a pr?
