### ISSUE TITLE
Project Setup Error 

### ISSUE THREAD

**Issue by Jaan19867** [code100x/daily-code#110]
while setting this project . I am getting error 

(node:76266) NOTE: The AWS SDK for JavaScript (v2) will enter maintenance mode
on September 8, 2024 and reach end-of-support on September 8, 2025.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check blog post at https://a.co/cUPnyil
(Use `node --trace-warnings ...` to show where the warning was created)
(base) riz@riz-Aspier-XXXX:~/Desktop/Open Source/harkirat-projects/daily-code/my-turborepo$ .

**Comment by anuragnegi000** [comment]
this should not be in the issue @hkirat
