### ISSUE TITLE
Migrating to postgres

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#113]
I feel like this'll just get harder and harder as time goes by

We don't have dependency on auth right now so the best time to move off of it

Let's migrate over to postgres + prisma and get rid of firebase completely

This is the schema of the DB right now - 

Tracks
<img width="1329" alt="Screenshot 2024-04-02 at 8 39 49 PM" src="https://github.com/code100x/daily-code/assets/8079861/ac6ca0b0-fbf5-4559-9402-761a2aa122f1">

Problems
<img width="1357" alt="Screenshot 2024-04-02 at 8 39 59 PM" src="https://github.com/code100x/daily-code/assets/8079861/f1d3c7e1-eaa5-401d-abdb-3913771c2b40">

So the final DB should be like this - 
Tracks
title
description
image
visible: boolean

Problems
title
description
type: "blog" | "code"

track_problems
id
problem_id
track_id
sort_order

**Comment by Rash-Hit** [comment]
100 %

**Comment by Rash-Hit** [comment]
@hkirat  So till then will be only working on frontend of 

![image](https://github.com/code100x/daily-code/assets/73944177/9b477b0e-035e-41aa-80a0-67709b741b7b)

**Comment by nimit9** [comment]
I'd like to work on migrating to prisma. @hkirat

**Comment by nimit9** [comment]
But we'll need auth later along with this right?

**Comment by nimit9** [comment]
Will we also need to write a script to get the data from firebase db populate it to the sql db?

**Comment by hkirat** [comment]
Auth can be deferred to later yes

**Comment by hkirat** [comment]
I've added prisma, @nimit9 can u add backend endpoints to nextjs so we can get rid of all the firebase calls?

**Comment by nimit9** [comment]
Yes, will do that

**Comment by nimit9** [comment]
I had one doubt @hkirat why do we need many to many relationship between tracks and problems?

**Comment by hkirat** [comment]
@nimit9  that would be great

**Comment by hkirat** [comment]
On the many to one question -- We might have a single problem present in various tracks
We havent had that use case right now but we might in the future

**Comment by nimit9** [comment]
Already working on it.

**Comment by nimit9** [comment]
> On the many to one question -- We might have a single problem present in various tracks
> We havent had that use case right now but we might in the future

Okay, got it, thanks!
