### ISSUE TITLE
Appbar design is bonked, Slides dropdown is also bonked

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#118]
<img width="953" alt="Screenshot 2024-04-03 at 3 18 39 AM" src="https://github.com/code100x/daily-code/assets/8079861/761ad281-c79c-4ddb-a213-c4b069271b93">

**Comment by nimit9** [comment]
Fixing this, missed a firebase backend call for the slides dropdown.

**Comment by nimit9** [comment]
Fixed the slides dropdown, can someone fix the appbar css?

**Comment by rohithreddy009** [comment]
> Fixed the slides dropdown, can someone fix the appbar css?

I can fix
