### ISSUE TITLE
Creating a note button to add notes 

### ISSUE THREAD

**Issue by krishna9358** [code100x/daily-code#124]
Along with the notes on daily-code, every individual has there own some points to add in the notes. We can create a note button to add our points which we want to add on that particular part . It should reflect to particular user only.

**Comment by nimit9** [comment]
I'll like to work on this if you won't be taking this up yourself.

Can store the notes in localstorage for now, and add it to db once we integrate auth.

@hkirat please assign it to me if feature is needed

**Comment by hkirat** [comment]
Lets finish auth first

**Comment by krishna9358** [comment]
Could you explain more for auth thing.  So that, I too can contribute or
help you.

**Comment by hkirat** [comment]
I think @nimit9  is already working on auth
After that is done feel free to pick this @krishna9358
