### ISSUE TITLE
Replace firebase auth with nextauth

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#127]
Use 
1. Login with google
2. Login with github

**Comment by nimit9** [comment]
Taking this up

**Comment by nimit9** [comment]
Hey @hkirat, should we use Prisma Adaptor for nextauth?

**Comment by krishna9358** [comment]
Not experienced in this but would love try it @hkirat

**Comment by theSahilThadani** [comment]
working on it !!

**Comment by nimit9** [comment]
> working on it !!

Already done in #129
