### ISSUE TITLE
Allow hidden tracks

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#13]
`hidden` field on a track should mean it isn't exposed on the frontend. 
For ex, I want to hide this track 
<img width="1549" alt="Screenshot 2024-02-01 at 1 26 07 AM" src="https://github.com/hkirat/daily-code/assets/8079861/0fd192cc-6789-47f6-a2da-8983182351c9">

**Comment by shreyas0924** [comment]
Is it like a button called "hide" and then it'll go to hidden tracks?

**Comment by hkirat** [comment]
This should actually be `visible` set to `true` so they are hidden by default

**Comment by Vivek-1102** [comment]
Sorry but i couldn't understand what ur trying to say ? 
 MY ASSUMPTION :
       They where already hidden by default and harkirat you make them visible by turning the boolean visible variable as true

**Comment by hkirat** [comment]
yes that is correct. We want everything to be hidden by default and if `visible` is set to true, it should be returned by the backend api
