### ISSUE TITLE
To add SSG, to avoid redeployment of the website after every post added

### ISSUE THREAD

**Issue by mvp5464** [code100x/daily-code#137]
**PROBLEM**
Whenever a new notion doc is uploaded, the site has to redeploy manually

**SOLUTION**
To generate static site after every time interval (eg. 5 min / 10 min / 1 hr)

**Comment by mvp5464** [comment]
Hi, @hkirat Sir, I have completed this assignment. Should I go for PR

**Comment by bhutoria** [comment]
Hey @mvp5464 , I didn't know that we had to create an issue first. As a result I have already created a pull request #136 . 

Did you use a similar approach, also, did you face the issue with ESLint as well regarding named exports?

**Comment by mvp5464** [comment]
Ok then I will not create the PR for this issue.

Yes same problem.

**Comment by bhutoria** [comment]
How did you solve it? can you check the file changes in the pr and let me know if you had a different approach? thanks.

**Comment by mvp5464** [comment]
**Added Revalidation whenever the backend endpoint is hit**
- We can add this to a button which is used to upload the notion docs (so if successfully uploaded then hit this link) [as TracksEditor.tsx is empty so not able to do that]
- So It won't render in intervals but only when the notion doc is uploaded.
-  @hkirat sir, Is this good or need to add something else

[Screencast.webm](https://github.com/code100x/daily-code/assets/28997328/ef757f71-1ef6-47b3-bb2d-cbb8a29844b6)

**Comment by mvp5464** [comment]
> How did you solve it? can you check the file changes in the pr and let me know if you had a different approach? thanks.

In time duration I had done alsmost the same

**Comment by bhutoria** [comment]
Your backend revalidation request is something even I am trying. Can you share your implementation here?

**Comment by mvp5464** [comment]
> Your backend revalidation request is something even I am trying. Can you share your implementation here?

Sure, I am pushing PR but it is giving  me type error

**Comment by bhutoria** [comment]
it looks good on the video.
can you share the code snippet here? 
of the backend request function and implementation on the front end?

**Comment by mvp5464** [comment]
> * So It won't render in intervals but only when the notion doc is uploaded.

Made PR So check it there and if any doubt or any suggestions mention me.

**Comment by nimit9** [comment]
> **Added Revalidation whenever the backend endpoint is hit**
> - We can add this to a button which is used to upload the notion docs (so if successfully uploaded then hit this link) [as TracksEditor.tsx is empty so not able to do that]
> - So It won't render in intervals but only when the notion doc is uploaded.
> -  @hkirat sir, Is this good or need to add something else
> 
> [Screencast.webm](https://github.com/code100x/daily-code/assets/28997328/ef757f71-1ef6-47b3-bb2d-cbb8a29844b6)
> 

Hey, currently there is no backend endpoint being hit for uploading the notionDoc. The file seed.ts is used to fill the data locally.

**Comment by bhutoria** [comment]
Check out #141 .. your implementation is top notch, however shouldn't we add an api route to the next app since we are using the app router and not the pages router?

you can check out the code and let me know if I am assuming incorrectly.

**Comment by mvp5464** [comment]
Hi @bhutoria, PR #138  has been created for this issue, so kindly close the duplicate PR #141.

I read that it may create conflict, So suggested to created this pages directory. page directory should be in the same level as the app directory. If this is wrong I will change my PR to add it back to an api route. 

BTW, Thank you for your suggestions, and if have any doubt happy to help on this issue

**Comment by bhutoria** [comment]
yeah, we are using Next v14, so we should use app router.

**Comment by mvp5464** [comment]
OK, Thanks will update the PR

**Comment by mvp5464** [comment]
closed #138
