### ISSUE TITLE
feat/Add Admin Dashboard with complete control

### ISSUE THREAD

**Issue by bhutoria** [code100x/daily-code#142]
# Add Admin Dashboard with ability to add tracks, edit tracks, create MCQ questions, create code questions 

- Tracks should be added directly from the dashboard with ability to revalidate ssg cache for each track.
- MCQ questions can be added for each track directly through the dashboard
- Code problems (as #112 )

Would like to work on this - since people are working on DSA problems and mcq already - could only work on creating tracks and revalidating cache.

**Comment by shashankdaima** [comment]
hey I can do it. Does it have to be approved by someone? (I am new here)..

**Comment by bhutoria** [comment]
@hkirat, would like to work on this, can this be assigned to me?

**Comment by ShubhamMewara** [comment]
it is done #152

**Comment by bhutoria** [comment]
Looks good. 

Doesn't seem to be protected by authentication though and we need to link every track to a set of problems - i.e, tracks and problems have a one to many relationship.

**Comment by ShubhamMewara** [comment]
@bhutoria  #127 is not merged we don't have auth right now. will work on that
