### ISSUE TITLE
Arrow keys takes the user to a weird page

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#146]
<img width="673" alt="Screenshot 2024-04-08 at 5 31 03 AM" src="https://github.com/code100x/daily-code/assets/8079861/2f617910-1820-422c-9da4-b4d68b470b0d">

**Comment by pantharshit007** [comment]
@hkirat  is it in production? since the issue still persists
![image](https://github.com/code100x/daily-code/assets/97608579/8556e98b-d150-46af-b270-0d0c55bcef23)
