### ISSUE TITLE
Add Home Button in the Appbar  to Navigate to Home Page  

### ISSUE THREAD

**Issue by shimiltharayil** [code100x/daily-code#150]
![Screenshot 2024-04-08 at 8 55 19 PM (2)](https://github.com/code100x/daily-code/assets/109408967/fdf77749-d7ee-4c90-ba8f-b54cb0600f7b)

**Comment by shashankdaima** [comment]
yo! I can take it. 
Will it have to be approved by @hkirat or someone else?

**Comment by ronitsharma03** [comment]
@shimiltharayil is this available to work on??

**Comment by vatan45** [comment]
small change in the appbar  <Button
            variant={"outline"}
            onClick={() => {
              router.push("/");
            }}
          >
            Home
          </Button>

**Comment by shashankdaima** [comment]
we should wait till someone confirms, as although the change is very small, but is the feature even required?

**Comment by rudrcodes** [comment]
Hey, I'll take the issue.
Can this issue be assigned to me?

**Comment by mvp5464** [comment]
Click on daily code logo it will redirect to home page

**Comment by async-avi** [comment]
#270 Issue resolved here

**Comment by hkirat** [comment]
Just do it on the dailycode logo click
