### ISSUE TITLE
Adding Bookmark button in notes

### ISSUE THREAD

**Issue by sagarb2003** [code100x/daily-code#160]
Users can mark their favorite notes by clicking on a bookmark button. When they want to see these saved notes later, they can find them in the bookmark section of the website's menu, but only if they've logged into their account. If someone tries to mark a note as a favorite without logging in, they'll be asked to log in first through a pop-up message

@hkirat can u assign this issue to me.
I am not familiar with firebase but will sureshot give my best to solve this.

**Comment by piyushhsainii** [comment]
@sagarb2003 @hkirat  is this the desired functionality? i have successfully integrated the bookmark feature just want to ask whether on bookmarking the note. it should bookmark single page or whole track!? 

![bookmark](https://github.com/code100x/daily-code/assets/134310734/d3ff80b4-2934-4cfd-bc78-9b61039fefb5)
