### ISSUE TITLE
Navigating between problems using Arrow keys results in ERROR

### ISSUE THREAD

**Issue by RitikBora** [code100x/daily-code#164]
When I try using arrow keys to navigate between problems of any chapter the redirection fails.

For example
If I'm on https://projects.100xdevs.com/tracks/6SbPPXGkG8QKFOTW9BmL/ts-1 and press the right arrow key, insted of redirecting to 
https://projects.100xdevs.com/tracks/6SbPPXGkG8QKFOTW9BmL/ts-2 it redirects to https://projects.100xdevs.com/tracks/6SbPPXGkG8QKFOTW9BmL/[object%20Object]

I tried replicating this on local environment and everything works fine there. It just happens for me on the production website. Could anyone else confirm this?

**Comment by bhutoria** [comment]
I don't think the code has been pushed to production yet.

**Comment by RitikBora** [comment]
@bhutoria  yes seems to be the case.
