### ISSUE TITLE
Add content wide search

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#175]
Allow users to search deep inside the contents of the blogs
1. Should use something like algolia/elastic search
2. There should be a way to refresh it whenever the notion doc changes

**Comment by RaghavenderSingh** [comment]
@hkirat can you assign it to me

**Comment by sameet11** [comment]
on it.

**Comment by SujithThirumalaisamy** [comment]
**Proposal of the approach**:
**Procedure**:
1. Add or Use a existing cache DB
2. Create a function addSearchTokenToCacheDB
3. Call it everytime admin creates a track
4. Create a GET /search endpoint (Which returns a array of links which are inside the token with the key as x which is a superset of the search query)

![image](https://github.com/code100x/daily-code/assets/108384868/7444629a-172e-4839-8020-2be9d7db8388)

Expecting this feature to be added with a deep discussion and implementation plan.

**Comment by nimit9** [comment]
Will it be able to search from the notion Doc?

**Comment by SujithThirumalaisamy** [comment]
We should fetch the notion doc somehow and feed the data to the token generation and store it in the datastore or some kind of cache to be fast enough

**Comment by SujithThirumalaisamy** [comment]
```typescript
import { NextRequest, NextResponse } from "next/server";
import { NotionAPI } from "notion-client";
const { Client } = require("@notionhq/client");
const { NotionToMarkdown } = require("notion-to-md");

export async function GET(req: NextRequest) {
  const id: string = req.nextUrl.searchParams.get("id") || "";
  const blocks = await getAllBlocks(id);
  console.log(blocks);
  const blocksId = Object.values(blocks);
  const result = [];
  for (const block of blocksId) {
    const data = await parseNotionToMarkDown(block);
    result.push(data);
  }

  return NextResponse.json(result);
}
const getAllBlocks = async (id: string) => {
  const notion = new NotionAPI();
  try {
    const pages = await notion.getPage(id);
    const data = await notion.getBlocks(Object.keys(pages.block));
    return data.recordMap.block;
  } catch (e) {
    const data = await notion.getPage(id);
    return data;
  }
};

const parseNotionToMarkDown = async (id) => {
  const notion = new Client({
    auth: process.env.NOTION_API_KEY,
  });

  const n2m = new NotionToMarkdown({ notionClient: notion });
  const mdblocks = await n2m.pageToMarkdown(id);
  const mdString = n2m.toMarkdownString(mdblocks);
  return mdString.parent;
};


```
>Create a api end point which generates a markdown for pages. We can further create tokens are change this to JSON and can directly store in on premis elastic search. @hkirat Looking for you suggessions man. But we need a notion api token for this. And all out notion docs should be added to the connection with the api. 

>Looking for existing libraries to do the fetching without the key

**Comment by sameet11** [comment]
are we creating a Search functionality to search data from the whole track or to search data only from a single page of the track @hkirat @SujithThirumalaisamy

**Comment by SujithThirumalaisamy** [comment]
Yes exactly, But I cannot proceed until we have access to the API. Ready with a elastic search local setup in my homelab server.

**Comment by ShubhamMewara** [comment]
hey @hkirat 
I have used algolia.com to search
Would you like to remove the previous search or want to keep it?


https://github.com/code100x/daily-code/assets/136337515/5989d79f-bf68-40e1-af18-2c186d69457b

**Comment by D3vq** [comment]
hi @ShubhamMewara , did you added the deep search for the whole blog( notion doc as well)?

**Comment by ShubhamMewara** [comment]
@D3vq yes i did

**Comment by D3vq** [comment]
@ShubhamMewara can we connect on discord, my username is mister0261 if you want to connect

**Comment by ShubhamMewara** [comment]
@D3vq ok
