### ISSUE TITLE
Make navbar of pages more responsive for smaller screen

### ISSUE THREAD

**Issue by mvp5464** [code100x/daily-code#182]
Now, navbar for smaller screen is not very responsive

Make navbar more responsive for smaller screen for better readability 

- Before
![Screenshot_Before](https://github.com/code100x/daily-code/assets/28997328/263f94e8-a878-4110-b01a-2616e27a22e1)

- After
![Screenshot_After](https://github.com/code100x/daily-code/assets/28997328/a7a3af83-c0c2-4ee8-8e28-125cc6bef5d7)

**Comment by mvp5464** [comment]
closing with new PR #184, As this PR has also push old codes

**Comment by omdhede** [comment]
Check-out my changes
Thanks
