### ISSUE TITLE
npx prisma migrate dev FAILING.. need help

### ISSUE THREAD

**Issue by shubhamrawat090** [code100x/daily-code#196]
I did these steps
1. Updated my fork
2. Cloned the repo
3. Ran yarn install
4. cd /packages/db
5. cp .env.example .env
6. Created a postgres container via docker
7. replaced the db URL with **DATABASE_URL="postgresql://postgres:mysecretpassword@localhost:5432/postgres"** in .env
8. npx prisma migrate dev **here is where it fails**

![Screenshot 2024-04-12 221140](https://github.com/code100x/daily-code/assets/58658277/e10be441-e0aa-4d8e-b319-894d1adf424e)

I am using a windows machine. I don't know if that's causing any issues. If yes, then urgent help is needed there.
What I have noticed that it searches in this path **D:\Harkirat_Codebase\daily-code\node_modules\node_modules\prisma\build\index.js**
Here node_modules is 2 times in the path. How did it take this path and how to I change/fix this.

**ANYONE WHO HAS RAN INTO THIS ISSUE AND FIXED IT PLEASE DO HELP.**

**Comment by piyushhsainii** [comment]
i ran this into this issue

solution - 

cd into /packages/db/prisma

then run cmd `yarn add prisma `

then run `npx prisma migrate dev`

and it fixed my error

**Comment by vibhaw1904** [comment]
@shubhamrawat090  you can run 
1.yarn prisma migrate dev
2.yarn seed:db

working for me

**Comment by shubhamrawat090** [comment]
@vibhaw1904 Thanks these helped. I'll push a PR for having these in the readme.

**Comment by omdhede** [comment]
use `yarn add prisma typescript ts-node @types/node --save-dev` in package/db
`cd package/db`
`yarn add prisma typescript ts-node @types/node --save-dev`

it works

**Comment by SohailGidwani** [comment]
![image](https://github.com/code100x/daily-code/assets/65704926/2f21a169-9aa6-486c-9280-96febc28f302)

even after performing the given steps I'm still getting this error

**Comment by kris08052000** [comment]
Even I am facing this "Module not found " issue. With all the try.

**Comment by SohailGidwani** [comment]
1.It migrates perfectly
2. When I try to seed the DB it gives this first
![image](https://github.com/code100x/daily-code/assets/65704926/91910552-241a-4b97-951e-f35072c7167c)
3. then I ran this command yarn add typescript ts-node @types/node  
installed all of it
4. then again if I try to seed the DB it gives this
![image](https://github.com/code100x/daily-code/assets/65704926/7526cc79-d3e1-4d0e-a012-1bda791bd001)

**Comment by manavkush** [comment]
> 1.It migrates perfectly 2. When I try to seed the DB it gives this first ![image](https://private-user-images.githubusercontent.com/65704926/322213216-91910552-241a-4b97-951e-f35072c7167c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjA0NjAsIm5iZiI6MTcxMzAyMDE2MCwicGF0aCI6Ii82NTcwNDkyNi8zMjIyMTMyMTYtOTE5MTA1NTItMjQxYS00Yjk3LTk1MWUtZjM1MDcyYzcxNjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE0NTYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxODE3MDEwZTUyNDA0MzA0NmE3MmE4OGVjNTUxYWVmYTRjYmM0OGZiYmRiNGFjMTQ3MmM0NjQxYmRmZjZiNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ovIV0h7NGPjpofGfwBBqKXF9B0l_H0uao-ojh_TAPTQ) 3. then I ran this command yarn add typescript ts-node @types/node installed all of it 4. then again if I try to seed the DB it gives this ![image](https://private-user-images.githubusercontent.com/65704926/322213314-7526cc79-d3e1-4d0e-a012-1bda791bd001.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjA0NjAsIm5iZiI6MTcxMzAyMDE2MCwicGF0aCI6Ii82NTcwNDkyNi8zMjIyMTMzMTQtNzUyNmNjNzktZDNlMS00ZDBlLWEwMTItMWJkYTc5MWJkMDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE0NTYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMTgzZDAyMGUyZTNiYTNlYTE1MDA5MzY3MTRkMDBmNDU4MDQwZjU5ZDdjYzA5ZGFiYTg1MDQ0ZjY2ODhhYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rYWBBjhUwQUPX4Gz2kIc-IbHDlds-90wKV7Z-kx4ekk)

I'm having the same issue.

**Comment by shubhamrawat090** [comment]
> 1.It migrates perfectly 2. When I try to seed the DB it gives this first ![image](https://private-user-images.githubusercontent.com/65704926/322213216-91910552-241a-4b97-951e-f35072c7167c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjEwNDIsIm5iZiI6MTcxMzAyMDc0MiwicGF0aCI6Ii82NTcwNDkyNi8zMjIyMTMyMTYtOTE5MTA1NTItMjQxYS00Yjk3LTk1MWUtZjM1MDcyYzcxNjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE1MDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YjFkNTQwMmQzMmQyOTMwMjk1M2Y4MWYwZjAyMjU4MjIxZmU0MzgzMzIwZjBkZDYwNTM3YTliM2E2ZWFlNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sewT_dGgrRc98dToSK02YZkWXqXaoikQNF3bMJV095M) 3. then I ran this command yarn add typescript ts-node @types/node installed all of it 4. then again if I try to seed the DB it gives this ![image](https://private-user-images.githubusercontent.com/65704926/322213314-7526cc79-d3e1-4d0e-a012-1bda791bd001.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjEwNDIsIm5iZiI6MTcxMzAyMDc0MiwicGF0aCI6Ii82NTcwNDkyNi8zMjIyMTMzMTQtNzUyNmNjNzktZDNlMS00ZDBlLWEwMTItMWJkYTc5MWJkMDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE1MDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzY2MyZGM0NmU3Mzc4OWY2NWE2NDUyZWZjN2U0NGM4NWRmY2RkZmZlYWY5Nzc5NDAxZTllYTRmZjI5YWM1ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.otVONKHN588Si9qkDBwfC0MQNnBxQoyXGNm2zivjlKE) 5. and same for the yarn command ![image](https://private-user-images.githubusercontent.com/65704926/322213503-c05212d6-5c87-4247-b828-11668f3727e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjEwNDIsIm5iZiI6MTcxMzAyMDc0MiwicGF0aCI6Ii82NTcwNDkyNi8zMjIyMTM1MDMtYzA1MjEyZDYtNWM4Ny00MjQ3LWI4MjgtMTE2NjhmMzcyN2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE1MDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MGY2ZmM0YzAzMGJjZjcwNmZiNmNjNGZiYzhjYmQzMWQxZGI5MTFmMWZkOTkzY2VhNmZhMzNjZDdkMDg1MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UPNLsEJMsur0qB89VD89VeFlwgrC86-_St4smofRC4M)

Try clearing your DB and then prisma generate + seed again. 
Or what I did was started a new postgres container and re-ran migrate + generate + seed again and that fixed it for me.

**Comment by SohailGidwani** [comment]
> > 1.It migrates perfectly 2. When I try to seed the DB it gives this first ![image](https://private-user-images.githubusercontent.com/65704926/322213216-91910552-241a-4b97-951e-f35072c7167c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjEwNDIsIm5iZiI6MTcxMzAyMDc0MiwicGF0aCI6Ii82NTcwNDkyNi8zMjIyMTMyMTYtOTE5MTA1NTItMjQxYS00Yjk3LTk1MWUtZjM1MDcyYzcxNjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE1MDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YjFkNTQwMmQzMmQyOTMwMjk1M2Y4MWYwZjAyMjU4MjIxZmU0MzgzMzIwZjBkZDYwNTM3YTliM2E2ZWFlNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sewT_dGgrRc98dToSK02YZkWXqXaoikQNF3bMJV095M) 3. then I ran this command yarn add typescript ts-node @types/node installed all of it 4. then again if I try to seed the DB it gives this ![image](https://private-user-images.githubusercontent.com/65704926/322213314-7526cc79-d3e1-4d0e-a012-1bda791bd001.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjEwNDIsIm5iZiI6MTcxMzAyMDc0MiwicGF0aCI6Ii82NTcwNDkyNi8zMjIyMTMzMTQtNzUyNmNjNzktZDNlMS00ZDBlLWEwMTItMWJkYTc5MWJkMDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE1MDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzY2MyZGM0NmU3Mzc4OWY2NWE2NDUyZWZjN2U0NGM4NWRmY2RkZmZlYWY5Nzc5NDAxZTllYTRmZjI5YWM1ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.otVONKHN588Si9qkDBwfC0MQNnBxQoyXGNm2zivjlKE) 5. and same for the yarn command ![image](https://private-user-images.githubusercontent.com/65704926/322213503-c05212d6-5c87-4247-b828-11668f3727e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjEwNDIsIm5iZiI6MTcxMzAyMDc0MiwicGF0aCI6Ii82NTcwNDkyNi8zMjIyMTM1MDMtYzA1MjEyZDYtNWM4Ny00MjQ3LWI4MjgtMTE2NjhmMzcyN2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE1MDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MGY2ZmM0YzAzMGJjZjcwNmZiNmNjNGZiYzhjYmQzMWQxZGI5MTFmMWZkOTkzY2VhNmZhMzNjZDdkMDg1MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UPNLsEJMsur0qB89VD89VeFlwgrC86-_St4smofRC4M)
> 
> Try clearing your DB and then prisma generate + seed again. Or what I did was started a new postgres container and re-ran migrate + generate + seed again and that fixed it for me.

I did try this, but I suppose the issue is with Neon db, it takes longer than 10 secs to seed the remote db so it fails

**Comment by shubhamrawat090** [comment]
> > > 1.It migrates perfectly 2. When I try to seed the DB it gives this first ![image](https://private-user-images.githubusercontent.com/65704926/322213216-91910552-241a-4b97-951e-f35072c7167c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjEwNDIsIm5iZiI6MTcxMzAyMDc0MiwicGF0aCI6Ii82NTcwNDkyNi8zMjIyMTMyMTYtOTE5MTA1NTItMjQxYS00Yjk3LTk1MWUtZjM1MDcyYzcxNjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE1MDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YjFkNTQwMmQzMmQyOTMwMjk1M2Y4MWYwZjAyMjU4MjIxZmU0MzgzMzIwZjBkZDYwNTM3YTliM2E2ZWFlNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sewT_dGgrRc98dToSK02YZkWXqXaoikQNF3bMJV095M) 3. then I ran this command yarn add typescript ts-node @types/node installed all of it 4. then again if I try to seed the DB it gives this ![image](https://private-user-images.githubusercontent.com/65704926/322213314-7526cc79-d3e1-4d0e-a012-1bda791bd001.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjEwNDIsIm5iZiI6MTcxMzAyMDc0MiwicGF0aCI6Ii82NTcwNDkyNi8zMjIyMTMzMTQtNzUyNmNjNzktZDNlMS00ZDBlLWEwMTItMWJkYTc5MWJkMDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE1MDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzY2MyZGM0NmU3Mzc4OWY2NWE2NDUyZWZjN2U0NGM4NWRmY2RkZmZlYWY5Nzc5NDAxZTllYTRmZjI5YWM1ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.otVONKHN588Si9qkDBwfC0MQNnBxQoyXGNm2zivjlKE) 5. and same for the yarn command ![image](https://private-user-images.githubusercontent.com/65704926/322213503-c05212d6-5c87-4247-b828-11668f3727e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjEwNDIsIm5iZiI6MTcxMzAyMDc0MiwicGF0aCI6Ii82NTcwNDkyNi8zMjIyMTM1MDMtYzA1MjEyZDYtNWM4Ny00MjQ3LWI4MjgtMTE2NjhmMzcyN2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE1MDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MGY2ZmM0YzAzMGJjZjcwNmZiNmNjNGZiYzhjYmQzMWQxZGI5MTFmMWZkOTkzY2VhNmZhMzNjZDdkMDg1MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UPNLsEJMsur0qB89VD89VeFlwgrC86-_St4smofRC4M)
> > 
> > 
> > Try clearing your DB and then prisma generate + seed again. Or what I did was started a new postgres container and re-ran migrate + generate + seed again and that fixed it for me.
> 
> I did try this, but I suppose the issue is with Neon db, it takes longer than 10 secs to seed the remote db so it fails

In that case I suggest using docker to run a postgres container locally and using that. It will be much faster that way.

**Comment by ganeshkondaka** [comment]
> yarn add prisma typescript ts-node @types/node --save-dev

do we need to install the prisma separately...?, but why it is not in the docker file
just asking
