### ISSUE TITLE
Seeding data to track table before categories and trackCategory table

### ISSUE THREAD

**Issue by vishalmishraa** [code100x/daily-code#201]
## Description
When seeding data to the database, we need to ensure that the `track` table is populated before the `categories` and `trackCategory` table, as there are dependencies between these tables.

![Screenshot 2024-04-13 at 1 03 38 AM](https://github.com/code100x/daily-code/assets/64027486/45e1d1e8-ab20-4535-85d7-a51c4e26e9ca)

## Proposed Solution
Modify the seeding script to await the creation of records in the `track` table before proceeding to create records in the `categories` and `trackCategory` table. This can be achieved by awaiting `Promise.all(promises)` before creating records in the `categories` and `trackCategory` table.

## Additional context
This issue was identified while working on the seeding script in `seed.ts`.

**Comment by RahulMishra0722** [comment]
Go to seed.ts and add this line in create fixxed  sortingOrder: 1, 

<img width="950" alt="Screenshot 2024-04-13 at 2 21 00 AM" src="https://github.com/code100x/daily-code/assets/119395914/e9c94b9e-a378-4194-92f7-11041a864786">

**Comment by vishalmishraa** [comment]
> Go to seed.ts and add this line in create fixxed  sortingOrder: 1, 
> 
> <img width="950" alt="Screenshot 2024-04-13 at 2 21 00 AM" src="https://github.com/code100x/daily-code/assets/119395914/e9c94b9e-a378-4194-92f7-11041a864786">
> 

It is already there in seedData.ts file which is used to extract seed

**Comment by Neon-20** [comment]
Did you run npx prisma migrate in correct path?
This doesnt seem like an issue tho'.
As far as i can see ur path is /packages/db, but it shd be /packages/db/prisma when you run npx prisma migrate
@vishalmishraa

**Comment by vishalmishraa** [comment]
> Did you run npx prisma migrate in correct path?
> This doesnt seem like an issue tho'.
> As far as i can see ur path is /packages/db, but it shd be /packages/db/prisma when you run npx prisma migrate
> @vishalmishraa 

Yeah , first i did eun npx prisma db migrate, then npx prima db seed .  And  in /package/db , there is package.json which managed it for package/db/prisma . Anyways i fixed it 😅.. the promises are getting resolved after creation of catagory table which actually should be first get executed.

**Comment by RahulMishra0722** [comment]
> Did you run npx prisma migrate in correct path? This doesnt seem like an issue tho'. As far as i can see ur path is /packages/db, but it shd be /packages/db/prisma when you run npx prisma migrate @vishalmishraa

You can't do that because the prima migrate command is used to seed the db as well you can  do it  manually if you want to but its it does it with the migrate Command so if you cd into prima you won't have access to the seed.ts file look at my message just add one line to seed.ts and itll work

**Comment by Neon-20** [comment]
Ok, previously it used to work quite smoothly with just few commands when I did setup, although I did a hack of copying migrate.ts to seed.ts for initial seeding @RahulMishra0722

**Comment by vishalmishraa** [comment]
> Ok, previously it used to work quite smoothly with just few commands when I did setup, although I did a hack of copying migrate.ts to seed.ts for initial seeding @RahulMishra0722 

Yup ,  harkirat added the some codes , but he didn't moved the promise section to the right place , that's why it was giving error.

**Comment by vishalmishraa** [comment]
> Go to seed.ts and add this line in create fixxed sortingOrder: 1,
> 
> <img alt="Screenshot 2024-04-13 at 2 21 00 AM" width="950" src="https://private-user-images.githubusercontent.com/119395914/322134523-e9c94b9e-a378-4194-92f7-11041a864786.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NTg3NTksIm5iZiI6MTcxMjk1ODQ1OSwicGF0aCI6Ii8xMTkzOTU5MTQvMzIyMTM0NTIzLWU5Yzk0YjllLWEzNzgtNDE5NC05MmY3LTExMDQxYTg2NDc4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQyMTQ3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzI0OTk3Y2ZjMTcwN2IzNjljNmY0MDVmMjlkMmQ4OTc5NjBlOGFlY2Y2ZThlYjRmZTFjZTVkYjJmZmRkNmYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._iAe9cVZH2jVMV9Neh1YsN0c2r6y4BLAqoi0w03zlak">

i checked you repo of daily-code , it is behind some commits , so , it used to be work before ,but after the last commit , it get broked.
