### ISSUE TITLE
feature: Implement Clickable Logo/Header Link for Homepage Navigation

### ISSUE THREAD

**Issue by chiragcj27** [code100x/daily-code#207]
**Basic Description**
Add the functionality for users to navigate back to the homepage by clicking on the logo or header. This standard feature improves usability and provides intuitive navigation. Implementing this enhancement will enhance the overall user experience of the website.

**Problem :** 
there is no way of going back to the page showing all slides together after clicking one of the categories of the nav bar shown below.
<img width="1036" alt="Screenshot 2024-04-13 at 5 15 58 PM" src="https://github.com/code100x/daily-code/assets/127305936/cb55f14b-64db-4489-abc1-f77dbf264557">

**Solution :** 
Make the **Daily Code** header clickable and on clicking link it to the **HomePage**

**Comment by vishalmishraa** [comment]
> **Basic Description**
> Add the functionality for users to navigate back to the homepage by clicking on the logo or header. This standard feature improves usability and provides intuitive navigation. Implementing this enhancement will enhance the overall user experience of the website.
> 
> **Problem :** 
> there is no way of going back to the page showing all slides together after clicking one of the categories of the nav bar shown below.
> <img width="1036" alt="Screenshot 2024-04-13 at 5 15 58 PM" src="https://github.com/code100x/daily-code/assets/127305936/cb55f14b-64db-4489-abc1-f77dbf264557">
> 
> **Solution :** 
> Make the **Daily Code** header clickable and on clicking link it to the **HomePage**
> 

You can navigate back , you have to click on selected catagory again .

**Comment by chiragcj27** [comment]
I apologize that I didn't notice this, but don't you think this clickable logo feature is basic for every website and should be implemented.
