### ISSUE TITLE
npx prisma db seed is failing

### ISSUE THREAD

**Issue by manavkush** [code100x/daily-code#220]
Hey, I was setting up the daily-code project and everything worked well till the seeding step.
I've tried checking the `seed.ts`(what the error is showing), but don't seem to find any problem in that. 
Is someone else having similar issue?

![Screenshot from 2024-04-13 20-00-57](https://github.com/code100x/daily-code/assets/64668859/3d4851e8-9ae3-452f-96dd-0b3c214775ca)

**Comment by kris08052000** [comment]
1.cd daily-code
2.yarn install
3.cd /packages/db
4.cp .env.example .env
5.Update the .env file with the database url
6.yarn prisma migrate dev
7.yarn prisma db seed
8.cd ../..
9.yarn run dev


This could solve your issue. I went in this above steps and it worked well for me.

I don't know why the f!uck this "Module not found" issue occur every time when i i go with NPM, even it occurred for me while installing 100xdev.app (cms).
https://github.com/redwoodjs/redwood-tutorial/issues/64

**Comment by manavkush** [comment]
I've followed the same steps. Not sure what the issue is. Have tried to reinstall the whole project but still the same issue. 
Some lead that I found was regarding postgres itself, that it wasn't allowing to populate data due to failing of `unique constraints` for `id`.

**Comment by shubhamrawat090** [comment]
#196 this issue is discussed here as well.

**Comment by SujithThirumalaisamy** [comment]
> I've followed the same steps. Not sure what the issue is. Have tried to reinstall the whole project but still the same issue. Some lead that I found was regarding postgres itself, that it wasn't allowing to populate data due to failing of `unique constraints` for `id`.

The mostprobably you have the db seeded already. Nothing to worry

**Comment by kris08052000** [comment]
Solution to this problem is to add docker database and seed it. local db is faster and neon is slower

**Comment by manavkush** [comment]
The database was already preeseeded. Found the data in the Tracks table. The `yarn prisma migrate dev` itself seeded the database also. 
I think readme can be updated to not have confusion. @SujithThirumalaisamy Thanks! found the issue.

**Comment by manavkush** [comment]
Closing the issue as the it's resolved.
