### ISSUE TITLE
when you click on learning path twice it redirect to other page.

### ISSUE THREAD

**Issue by SarfrazAlame** [code100x/daily-code#231]
![Screenshot 2024-04-14 074453](https://github.com/code100x/daily-code/assets/132803649/8b7a919f-7ca9-4a3f-aa27-9147a1702126)

**Comment by Nishchay1571999** [comment]
This only resets the page to its default, so I do not think it is a problem.

**Comment by alphacoder-mp3** [comment]
Nothing is happening if you click twice or thrice or n number times to the Learning paths. Besides there's no onclick or event  triggering on learning paths. 
So this is not the issue.
