### ISSUE TITLE
feat: History Button! This feature allows you to easily revisit previously visited tracks and pages. 

### ISSUE THREAD

**Issue by iamgauravbisht** [code100x/daily-code#237]
issue: Accessing previously visited pages isn't straight forward , you have to search for them each time and then navigate to your desired page. This becomes frustrating, especially since many of us frequently copy and paste code from these pages

I've noticed another pull request proposing the addition of a "watch" button that directly links to the relevant video for a given topic. We could integrate this feature into our current setup by including a "video" button that links us to the appropriate video for the topic.

solution: Introducing an "H" (History button) in the app bar, which tracks visited pages and offers users the option to revisit them. I'm utilizing localStorage to remember the pages the user has visited.

https://github.com/code100x/daily-code/assets/97449434/6c22e369-0a73-44a2-8453-cf82fd464af2

**Comment by HellBats** [comment]
Do you mean that you want to add frequently visited pages or exact history of visited pages?

**Comment by iamgauravbisht** [comment]
Exact history of user

**Comment by iamgauravbisht** [comment]
> Do you mean that you want to add frequently visited pages or exact history of visited pages?

Exact history of visited pages

**Comment by iamgauravbisht** [comment]
> Do you mean that you want to add frequently visited pages or exact history of visited pages?

Exact history of visited pages but tracks will be unique.
