### ISSUE TITLE
bug: Error on the local server, says "Module not found: Can't resolve '@repo/common'"

### ISSUE THREAD

**Issue by SohailGidwani** [code100x/daily-code#255]
I'm trying to pull the code and ran all the command except the seed one (because it is not working for me).
And now when I do "yarn run dev"
1. it starts the server
2. Then I'm getting this error "Module not found: Can't resolve '@repo/common'"
web:dev: Module not found: Can't resolve '@repo/common'
web:dev:   2 |
web:dev:   3 | import { useEffect, useState } from "react";
web:dev: > 4 | import { getFunction } from "@repo/common";
web:dev:   5 | import { Button } from ".";
web:dev:   6 | import { useRouter } from "next/navigation";

![image](https://github.com/code100x/daily-code/assets/65704926/f5638a1f-1093-4e33-aa9e-78f08a5e47df)

I checked the comman-> package.json, it does have the "name": "@repo/common",

Can someone help me with this?

**Comment by ShubhamMewara** [comment]
Fixed in #254
