### ISSUE TITLE
feature: List all DSA  Problem Statements in the admin dashboard

### ISSUE THREAD

**Issue by nimit9** [code100x/daily-code#262]
### Note: Please only raise the PR for this once https://github.com/code100x/daily-code/pull/203 is reviewed and merged, since it is dependent on that.

- Add one more Tab for viewing the existing PS, integrate this with the current admin dashboard flow.
- Add a way for admins to edit those PS.

**Comment by SujithThirumalaisamy** [comment]
![image](https://github.com/code100x/daily-code/assets/108384868/51b4a4e5-5ae9-4e43-819d-79c5b9c2bd2d)
I think listing and editing of the problems are already there.

**Comment by nimit9** [comment]
Talking about PS, it is a separate table.

**Comment by SujithThirumalaisamy** [comment]
![image](https://github.com/code100x/daily-code/assets/108384868/ffdbf7c8-0564-43a3-b1a3-250384b1613c)
This is right?

**Comment by SujithThirumalaisamy** [comment]
Working on this. Will update within tonight. Have some refactoring for the imports of other data in the other admin tabs as well.

**Comment by SujithThirumalaisamy** [comment]
https://github.com/code100x/daily-code/assets/108384868/da1a2656-6fce-4d8f-a4a9-bf526d2c12ac

>Working on this. Suggessions?

**Comment by nimit9** [comment]
The test cases are based on the argument names provided, are you checking that.

I think you can just use the same form I've created to edit the PS.

**Comment by SujithThirumalaisamy** [comment]
> The test cases are based on the argument names provided, are you checking that.
> 
> I think you can just use the same form I've created to edit the PS.

![image](https://github.com/code100x/daily-code/assets/108384868/45c32ab9-5669-4790-9db7-1f54e694c133)
This right?

**Comment by nimit9** [comment]
No, `/admin/code/[problemId]/page.tsx`

**Comment by SujithThirumalaisamy** [comment]
> The test cases are based on the argument names provided, are you checking that.
> 
> I think you can just use the same form I've created to edit the PS.

Why can't we take the thing you done to the admin page. So everything will be in a single place?

**Comment by nimit9** [comment]
Yeah you can. I moved that to a separate page because it was a big form. Would have looked too cluttered on this page.

**Comment by SujithThirumalaisamy** [comment]
Will try to organise things a bit.

**Comment by SujithThirumalaisamy** [comment]
A good thing I think of is making this whole problem component a fullscreen dialog. So we can use this for editing and adding things. Without making things move crazyly in the page. Also can implement the JSON feature in the dialog itself.

**Comment by ASCE-D** [comment]
can we also take parameter type in the input because for
 other languages we would need those

**Comment by SujithThirumalaisamy** [comment]
> can we also take parameter type in the input because for other languages we would need those

Need a bit more arch changes. Like we should have some more thing to the db then. Will figure this next
