### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by deepak7mehra** [code100x/daily-code#265]
**Describe the bug**
Website is not working 

open (https://projects.100xdevs.com/)

**Screenshots or GIFs**

[Screenshot (180)](https://github.com/code100x/daily-code/assets/89858465/8e311537-23cb-4e1c-84aa-523d949918c0)

using chrome browser on windows

**Comment by sahajkedia** [comment]
Reproducing locally, it's coming as expected but in production there seems to be some problem

**Comment by SujithThirumalaisamy** [comment]
Please checknif the issue is already raised #264
