### ISSUE TITLE
feature: Adding checkbox to the tracks

### ISSUE THREAD

**Issue by nischal-shetty2** [code100x/daily-code#272]
**Is your feature request related to a problem? Please describe.**
cannot keep track of which tracks are done and which are left

**Describe the solution you'd like**
add checkbox for the tracks

https://github.com/code100x/daily-code/assets/136328410/bbe95853-e2a3-40ed-88c8-ad5155c1b675

**Comment by nischal-shetty2** [comment]
@hkirat @nimit9 please tell if a pr is required or is this feature not needed

**Comment by nimit9** [comment]
Someone had worked on bookmarking the tracks, I think this is the same thing, so not really needed I guess.

**Comment by nischal-shetty2** [comment]
> Someone had worked on bookmarking the tracks, I think this is the same thing, so not really needed I guess.

bookmarking is for future reference but i get you're point its the same implementation, alr thanks wont work on the backend then! should i close the issue or let @hkirat see it atleast?

**Comment by async-avi** [comment]
> Someone had worked on bookmarking the tracks, I think this is the same thing, so not really needed I guess.

bruh, having checkbox functionality and having bookmarks are very different things.

**Comment by nimit9** [comment]
Yeah, you're correct, my bad

**Comment by Neon-20** [comment]
Don't you think it's like overcomplicating things, introducing tons of features in just a simple repo. @nischal-shetty2 . well not pointing towards ur PR but saying in general, every other day a new feature pops up out of the blue.
Note: Checkbox and Bookmarks are almost the same.

**Comment by nischal-shetty2** [comment]
@Neon-20 that is true but when do we know where to draw the line, and if we stop suggesting featured then the website would not really improve. these are suggestions at the end of the day and kirat decides which ones to keep
