### ISSUE TITLE
UI UX Enhancement: Making the UI UX of Login more better @hkirat .

### ISSUE THREAD

**Issue by anshulsoni2010** [code100x/daily-code#274]
Hi Team,

Howdy, @hkirat ? I’m great! I found Daily Code this morning and was impressed by how I could improve its UI/UX. As a developer who also designs, I have a lot of ideas on how to make the login page more interesting.

May I join? Once you approve me, I would like to share the UI UX designs . Let’s take Daily Code to even greater heights!
After Designing , I will work code side

Thanks Team

**Comment by anshulsoni2010** [comment]
@hkirat assign me pls

**Comment by hkirat** [comment]
This would be great

**Comment by anshulsoni2010** [comment]
Sure, I'll raise the pr in some days as I am going on short trip.

:)

**Comment by anshulsoni2010** [comment]
Started work of this of this pr @hkirat - Will Raise PR By Tonight. 

Thank you

**Comment by shantanuSakpal** [comment]
@hkirat  @devsargam  close this issue pls
