### ISSUE TITLE
bug: Blank page when user clicks on slides button.

### ISSUE THREAD

**Issue by Shriom-Trivedi** [code100x/daily-code#278]
**Describe the bug**

**To Reproduce**
1. Click on the slides button when you go to the course
2. It shows a blank page

**Expected behavior**
- It should show the slides.

**Screenshots or GIFs**
[screen-capture.webm](https://github.com/code100x/daily-code/assets/32411707/8f912396-42d9-458e-8a4a-11dcbaf40546)

**Info (please complete the following information):**
 - Chrome

 - Version 123.0.6312.122 (Official Build) (64-bit)

**Additional context**
URL seems to be wrong - `https://projects.100xdevs.com/tracks/ABEC/[object%20Promise]`

**Comment by nimit9** [comment]
Hey, this issue is related to code100x/cms repo. Please post it there

**Comment by Shriom-Trivedi** [comment]
Hi Nimit,

Thanks for the info, will do it ASAP!

**Comment by Shriom-Trivedi** [comment]
Hi @nimit9, thanks for the info I've opened the issue on code100x/cms repo.

You can find the issue here: [Issue 426](https://github.com/code100x/cms/issues/426)

**Comment by Shriom-Trivedi** [comment]
@nimit9 you can close this issue.

**Comment by nimit9** [comment]
You can close this, I can't close it

**Comment by N4r35h** [comment]
i have confirmed it to be a bug here @nimit9 

@Shriom-Trivedi please have this issue reopened

i will have create a PR to fix this now

**Comment by nimit9** [comment]
What's the bug? @N4r35h

**Comment by Shriom-Trivedi** [comment]
@N4r35h done, you can go ahead!
