### ISSUE TITLE
feature: Add github Repo link next to the theme button

### ISSUE THREAD

**Issue by mittalsam98** [code100x/daily-code#284]
**Is your feature request related to a problem? Please describe.**
It would be better if we add the Github link of the repo to easily access the github repo

**Describe the solution you'd like**
A GitHub icon which follows to this github repo  in the navbar beside the theme toggle icon like this
![image](https://github.com/code100x/daily-code/assets/42431274/14380978-85b4-4b59-8a22-a66d9fdb5c2f)

I would like to raise PR for this if it is approved. @hkirat pls add your input

**Comment by amanasati01** [comment]
hey i can add a icon are you working on this?

**Comment by mittalsam98** [comment]
Hey @amanasati01, I have already raised a PR for this
