### ISSUE TITLE
feature: Feedback when clicked on "Daily Code" header which redirects to the home page.

### ISSUE THREAD

**Issue by akshatgoel07** [code100x/daily-code#302]
I'm also confused when I click on "Daily Code" header if I'm getting redirected to the home page or not, similarly for when I choose a path, **For example** On home page when I click on "Next Auth" path, it does not provide any **feedback** if the page is loading.

A simple loader would solve the problem.

**Comment by ssk090** [comment]
Hey @hkirat,

I have raised the PR for the same : https://github.com/code100x/daily-code/pull/305

Thanks
