### ISSUE TITLE
bug: Not able to run repo in dev mode.

### ISSUE THREAD

**Issue by vr1Ravi** [code100x/daily-code#313]
**Describe the bug**
While following all the instruction given on redme file to start this repo, when running 
yarn prisma db seed

getting an error :- 

PrismaClientKnownRequestError: 
Invalid `db.track.create()` invocation in
A:\daily-code\packages\db\prisma\seed.ts:9:32

  6 const promises: Promise<any>[] = [];
  7 seedsData.forEach((seed) => {
  8   if (!hashID.includes(seed.data.id)) {
→ 9     const promise = db.track.create(
Unique constraint failed on the fields: (`id`)

**To Reproduce**

Just clone the repo try running it locally. When you come to 
yarn prisma db seed, you might see error in console.

**Screenshots or GIFs**
![Screenshot 2024-04-20 180412](https://github.com/code100x/daily-code/assets/103517405/437b44cb-c941-4f54-a1b7-c2e1263e1233)

**Comment by ShubhamMewara** [comment]
I think your DB is already populated check by using yarn Prisma studio in db folder.
Error is there is already a track present with the same ID.

**Comment by vr1Ravi** [comment]
I can see the models, but inside categories there is 0 record.

![Screenshot 2024-04-20 185039](https://github.com/code100x/daily-code/assets/103517405/26cc41bc-4ace-4659-a67b-92ed6b2a77b7)

while leads ui to this 

![Screenshot 2024-04-20 185240](https://github.com/code100x/daily-code/assets/103517405/aae60243-3a3c-49e7-a0f9-e8ac1b6976a2)
as we can see empty div below Laerning paths. could you tell me what I'm missing.

**Comment by ShubhamMewara** [comment]
just reset your db or delete all data and run `seed` again. or
comment/delete `seedsData.forEach` in seed.ts

**Comment by kumarsahil01** [comment]
try latest version @vr1Ravi  use .sh file and try to use the docker container it works fine for me

**Comment by Ameerjafar** [comment]
for this you should reset the migrate.The command for that is "npm run prisma migrate reset" and it should work fine.
