### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Yash-946** [code100x/daily-code#315]
**Describe the bug**
Error: [next-auth]: `useSession` must be wrapped in a `<SessionProvider />`

**To Reproduce**
1. After running the code next day
2. See error

**Expected behavior**

**Screenshots or GIFs**
![Screenshot 2024-04-21 094637](https://github.com/code100x/daily-code/assets/88927053/a083c607-c361-4a3c-876f-20af9a19f61c)

**Info (please complete the following information):**
 - Browser chrome
 - OS - Windows

**Additional context**
don't make any changes just followed the README file

**Comment by anshu-gautam** [comment]
I have picked this up
