### ISSUE TITLE
bug: Not able to navigate to 100xdevs

### ISSUE THREAD

**Issue by Aryanshu919** [code100x/daily-code#316]
**Describe the bug**
In the footer section when we click on 100xdevs image we are not able to navigate to 100xdevs website.

**Screenshots or GIFs**

<img width="1138" alt="Screenshot 2024-04-21 at 12 04 03 AM" src="https://github.com/code100x/daily-code/assets/92309448/62b34c74-7815-444b-a811-0cfe486f7e06">

**Comment by PrakharSinha-09** [comment]
there is no hyperlink attached @Aryanshu919
