### ISSUE TITLE
When the client is on other category they  will be able to see the All Categories Button/Select Component  in Landing Page

### ISSUE THREAD

**Issue by abhayymishraa** [code100x/daily-code#322]
like when i am in the web dev or lets say dsa category suppose a track you wanted to find you don't know what is its category and you are on other category  in this case we need to reload in order to get to all components back  but what if we have a All categories 

i always stuck in rememberring the name and category so whnever i am on the different track i need to reload 

i have fixed this feature issue 

**EXpected Behaviour**

- For Select Component

**when on landing page All Categories Select button must not appear**

![Screenshot from 2024-04-22 01-34-54](https://github.com/code100x/daily-code/assets/133818254/6f0a03b2-911b-4a79-8cd9-193c099ddf61)

**when user on different route it should appear then like this**

![Screenshot from 2024-04-22 01-36-35](https://github.com/code100x/daily-code/assets/133818254/1e8fea7d-eaba-4336-9cd4-271f184e6b36)

-For Button Component

_same as above_

![Screenshot from 2024-04-22 01-29-02](https://github.com/code100x/daily-code/assets/133818254/533c1877-a65d-4565-8744-9e2c1f253818)

**same behaviour as select compoent it should appear on different route**

![Screenshot from 2024-04-22 01-29-14](https://github.com/code100x/daily-code/assets/133818254/98b63802-17a9-43ba-9b8e-36372681d966)

**Comment by abhayymishraa** [comment]
I am working on this issue .

**Comment by vr1Ravi** [comment]
Why this issue is still open ?
