### ISSUE TITLE
bug: In light mode, the 100xdevs image and footer look unpleasant.

### ISSUE THREAD

**Issue by Aryanshu919** [code100x/daily-code#335]
**Describe the bug**
There is a discrepancy between the background color of the 100xdevs image and the color of the footer.

<img width="1166" alt="Screenshot 2024-04-22 at 10 06 44 PM" src="https://github.com/code100x/daily-code/assets/92309448/8af9916a-9e84-4722-bd84-dc410e462a08">

**Comment by ganicodes** [comment]
Hey @Aryanshu919 can I take this up?

**Comment by Aryanshu919** [comment]
@ganicodes  sure

**Comment by Abhi0049k** [comment]
Hey @Aryanshu919  can I work on this issue?
