### ISSUE TITLE
bug: Code Container overflows on mobile screen

### ISSUE THREAD

**Issue by Keshav-0907** [code100x/daily-code#343]
**Describe the bug**
The code snippet container is not responsive, and overflows on smaller screens

**To Reproduce**
1. Go to [https://projects.100xdevs.com/tracks/CI-CD/cicd-8](https://projects.100xdevs.com/tracks/CI-CD/cicd-8)
2. Check screen responsiveness

**Expected behavior**
The container should display a Horizontal scrollbar on smaller screens, enabling users to access the full content.

**Screenshots or GIFs**
<img width="634" alt="Screenshot 2024-04-24 at 12 59 38 AM" src="https://github.com/code100x/daily-code/assets/91189139/2c7c7387-2a6d-4873-a28c-03f22a368acd">

**Info (please complete the following information):**
 - Browser : Firefox
 - Version : 123.0

**Comment by rajiknows** [comment]
on it
