### ISSUE TITLE
feature: Add a quit button 

### ISSUE THREAD

**Issue by amanasati01** [code100x/daily-code#347]
Add a quit button if any player want to quit also send the message to another play that opponent quit the game

**Comment by amanasati01** [comment]
i have already solved the issue 
[Uploading Screencast from 2024-04-25 13-23-44.webm…]()

**Comment by amanasati01** [comment]
i have already solved this issue 
[Uploading Screencast from 2024-04-25 13-23-44.webm…]()

**Comment by amanasati01** [comment]
I have already solved the issue
![Screenshot from 2024-04-25 13-41-54](https://github.com/code100x/daily-code/assets/117284887/8ebb4433-db7b-466d-bc7f-d5518283e6e3)
![Screenshot from 2024-04-25 13-42-07](https://github.com/code100x/daily-code/assets/117284887/6dc66a77-5774-4653-908f-758c60436b73)

**Comment by dyaipayan22** [comment]
@amanasati01 wrong repository

**Comment by amanasati01** [comment]
i added by mistake i have to add in chess repo

**Comment by IAmRiteshKoushik** [comment]
I think this issue can be closed @hkirat
