### ISSUE TITLE
bug: Undefined reference to "scrollableContainerRef" in "SearchDialog"

### ISSUE THREAD

**Issue by CodeWhispererr** [code100x/daily-code#351]
**Describe the bug**
The code snippet is missing the part where scrollableContainerRef is created using useRef.
![image](https://github.com/code100x/daily-code/assets/80579894/e16a7a55-b1d3-4cdf-90d9-5248a729a7af)

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the project.
2. You will get this error  ↓
![image](https://github.com/code100x/daily-code/assets/80579894/311f0cde-5082-41fa-86cd-4a0fc258aa81)

**Expected behaviour**
The SearchDialog component should allow smooth scrolling of search results.

**Comment by abedin-ashraf** [comment]
![Screenshot from 2024-04-26 00-09-18](https://github.com/code100x/daily-code/assets/107454977/927015ed-3ba4-4609-af4e-1c68d535ce9a)
