### ISSUE TITLE
feature: Enhanced Social Icons (Style & Spacing) + GitHub Icon Added

### ISSUE THREAD

**Issue by CodeWhispererr** [code100x/daily-code#358]
This feature improves the overall design of the social icons in the footer. 
This includes changes to the icons themselves (style, size, colours)

**Current Icons and Colours**
![image](https://github.com/code100x/daily-code/assets/80579894/845f63e8-5b57-4e54-8a24-23d31ab57764)

**Describe the solution you'd like**
![image](https://github.com/code100x/daily-code/assets/80579894/eeb7928b-d987-4775-b6e4-7be0c0b09100)

**Comment by Vidit-Jain2206** [comment]
somebody is already working on this.
Check PR #365
