### ISSUE TITLE
bug: scrollableContainerRef not initiallized properly, throws error on start.

### ISSUE THREAD

**Issue by RohanGeorge23** [code100x/daily-code#360]
**Describe the bug**
Initialization of the variable scrollableContainerRef is missing!

**To Reproduce**
1. just clone and run the application
2. You will see the error
![image](https://github.com/code100x/daily-code/assets/59122596/745fb544-67ad-427d-8349-63da16cf9e96)

**Expected behavior**
The application should start normally

**Screenshots or GIFs**
![image](https://github.com/code100x/daily-code/assets/59122596/508f6b2d-cb1a-47de-b8d0-45f380c5e302)

**Info (please complete the following information):**
 - Browser : Chrome
 - Version : 24

**Additional context**

**Expected behavior**
A clear ion of the variable has a typezcable, add screenshots to help explain your problem.

**Info (please complete the following information):**

**Additional context**
Looks like someone had typo

**Comment by RohanGeorge23** [comment]
@hkirat when I tried to run the application, I saw there's a missing initialization

This is how it is :
  const  = useRef<HTMLDivElement>(null);

This is how it is supposed to be : 
  const scrollableContainerRef = useRef<HTMLDivElement>(null);

You can check this under ui/src/SearchDialog.tsx
Here's the link for your reference https://github.com/code100x/daily-code/blob/8ce213b69145e6f502dbbd9a623fb4fae38ceb02/packages/ui/src/SearchDialog.tsx#L14

**Comment by RohanGeorge23** [comment]
@hkirat Here's the PR.
[](https://github.com/code100x/daily-code/pull/361)

**Comment by CodeWhispererr** [comment]
PR is already present.

**Comment by RohanGeorge23** [comment]
My Bad
