### ISSUE TITLE
bug: Button Group alignment and background color of buttons in appbar

### ISSUE THREAD

**Issue by Abhi0049k** [code100x/daily-code#366]
### Describe the bug
The Button Group in the BlogAppbar component is not aligned vertically center and the buttons in appbar have a different background color

### To Reproduce the issue
1.  Open the web application.
2.  Open any learning path.
3.  Observe the position of the button group within the appbar.
4. Observer the background color of buttons in the appbar.

### Expected Behavior
1. The Button Group should be positioned in the center vertically
2. Buttons in the button group should have the same background color

### Screenshot
![image](https://github.com/code100x/daily-code/assets/112062354/62b9b5d2-6247-4ebb-96d0-2d01d4a53ff8)

#### Please checkmark the following checklist: 
- [X] I make sure that a similar issue is not opened

**Comment by CARPEDIEM05** [comment]
Hi @Abhi0049k , I have aligned them properly as expected but can you tell me the expected result number 2? As I can see all the buttons have same background color.

**Comment by Abhi0049k** [comment]
@hkirat @eltociear @ssk090 @mvp5464 Please notice the margin-bottom is more than the margin-top for the button- group and the background-color of buttons `prev`, `next` and `download` is different from background-color of buttons `Jump to` and theme toggle.
