### ISSUE TITLE
feature: Force login on daily code , dont show tracks w/o it

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#371]
time to get some emails

**Comment by nimit9** [comment]
On it

**Comment by YuZaGa** [comment]
Hi, @hkirat , I have created a PR with different approach(disabling access to tracks instead of hiding it) which would create a better and consistent flow across screens.

**Comment by Ameerjafar** [comment]
can i work on this @hkirat

**Comment by hkirat** [comment]
Still need to allow users to go to page 1 and 2 of a track before enfording login popup on the third page

**Comment by YuZaGa** [comment]
Disabled tracks after second page. #394
