### ISSUE TITLE
bug: ./setupDB.sh script in Git Bash gives MODULE_NOT_FOUND error when Local Docker setup is chosen in Windows 

### ISSUE THREAD

**Issue by rakeshs51** [code100x/daily-code#390]
**Describe the bug**
When Local DB with Docker is chosen for Database setup, I get the error, `Error: Cannot find module 'D:\Code\100x\daily-code-main\node_modules\node_modules\prisma\build\index.js' `

Since this error comes after Migrating DB log, this means it is produced by `npx prisma migrate dev` command.

Possible Solutions Tried:
- Deleting node_modules
- Reinstalling node js

**To Reproduce**
1. I am using Windows Machine
2. run ./setupDB.sh command inside Git Bash in rootDir/packages/db directory
3. Select Local DB with Docker Setup as config
4. An error saying `Error: Cannot find module 'D:\Code\100x\daily-code-main\node_modules\node_modules\prisma\build\index.js'` pops up.

**Expected behavior**
The project should run locally at the expected port. 

**Screenshots or GIFs**
![image](https://github.com/code100x/daily-code/assets/55094915/2e254b30-1885-4adb-bb45-d1baf802e5c2)

**Info (please complete the following information):**
 - Edge
 - Editor: VS Code

**Additional context**
- [Discord Chat on members facing similar issues](https://discordapp.com/channels/1171768226691162162/1177071437702508544/1236762770473488475)

**Comment by Amarprasad33** [comment]
I am also facing the same issue right now, does anyone know the fix ?

**Comment by iharsh02** [comment]
replace npx with yarn inside your setupDB.sh

![image](https://github.com/code100x/daily-code/assets/73895659/3f7b14ae-257f-4b80-acab-b415c64c2950)

**Comment by vr1Ravi** [comment]
@iharsh02 thank you, I was also facing the same issue. now solved

**Comment by vanshaj-sharma** [comment]
hey guys 👋  after using the fix provided by @iharsh02, I found that this fix will only for an offline set-up of the project and will cause errors when using docker compose watch, so use this fix iff when setting the project offline.

**Comment by ganeshkondaka** [comment]
do we need to install prisma separately
