### ISSUE TITLE
/bounty should trigger an entry to a google doc

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#391]
To keep things simple, before we have bounty-dispenser, we need a way to log all the bounties somewhere so we can track them effectively

@devsargam do u think this is easy to do?

**Comment by hkirat** [comment]
The ckoudflare fn can also post it on discord/tweet out at https://twitter.com/Techalerts101

**Comment by piyushhsainii** [comment]
> The ckoudflare fn can also post it on discord/tweet out at https://twitter.com/Techalerts101

can other people try to build this as well or it is assigned to sargam only?

**Comment by devsargam** [comment]
@hkirat yep very easy doable 100%

**Comment by hkirat** [comment]
@piyushhsainii do u want to do it?
@devsargam can u guide them?

**Comment by hkirat** [comment]
feel free to divide

**Comment by devsargam** [comment]
yeah can guide ofc

**Comment by devsargam** [comment]
@hkirat can u assign @piyushhsainii. I'll help if needed

**Comment by piyushhsainii** [comment]
> @piyushhsainii do u want to do it? @devsargam can u guide them?

Happy to contribute

**Comment by piyushhsainii** [comment]
@hkirat @devsargam  one question , i need to create a section in daily code where you can log the bounty details that will trigger the google doc ,right?

**Comment by devsargam** [comment]
Need to do some research here. I am guessing the core bot at https://github.com/code100x/github-sol-auto-dispenser is needed.

But I think should be a generic one to be used in cms, daily and chess too.

**Comment by Ameerjafar** [comment]
@piyushhsainii sir I want to work on this enhancement sir can you give me a chance to work on it if not no problem sir you carry on.

**Comment by devsargam** [comment]
Hey @Ameerjafar. @piyushhsainii has already started the work can u work on something else for now?

**Comment by Ameerjafar** [comment]
ok  @devsargam sir

**Comment by piyushhsainii** [comment]
@hkirat the automation-bot functionality is done, just need to add google doc now, sir can i use google sheet API for that? or strictly cloudfare is required?

**Comment by hkirat** [comment]
any API is fine
We need this asap can u PR whatever u have right now @piyushhsainii ?

**Comment by hkirat** [comment]
please acitvely open draft PRs so we can partially review it

**Comment by devsargam** [comment]
Hey @hkirat should this be a part of daily code or a standalone project?

**Comment by hkirat** [comment]
Probably standalone yeah

**Comment by hkirat** [comment]
https://github.com/code100x/bounty-hook

**Comment by devsargam** [comment]
Can u create a repo sth like bounty-tracker with just a readme @hkirat

**Comment by piyushhsainii** [comment]
> Probably standalone yeah
> 
> 

The Automation-Bot setup is done

- Automatic Discord Log is also setup

Should i PR this for now?

**Comment by nimit9** [comment]
Can't this be integrated with the bounty-dispenser only?

I was thinking of working on this, where the owner has the track of all the bounties on his dashboard in the bounty-dispenser. 

@devsargam @hkirat @piyushhsainii

**Comment by devsargam** [comment]
Yeah bounty dispenser is better but this should work as an intermediate solution as a lot of bounties are being dispatched right now hard to keep up

**Comment by hkirat** [comment]
we will need some sort of manual intervention in bounty bot. 
Its a lil unsafe having a private key on an aws server

**Comment by hkirat** [comment]
Also can get tricky in taxes if we do it via sol

**Comment by hkirat** [comment]
@devsargam https://github.com/code100x/bounty-hook

**Comment by nimit9** [comment]
Can't we do this on Zapier? Or is it expensive?

**Comment by devsargam** [comment]
No, github webhook hitting a hono app deployed on cloudflare fn should do it

**Comment by piyushhsainii** [comment]
@hkirat 'can you give me few hours, actually i forgot to push the code , bot setup and discord logging functionality is done, i am in college right now, have exam today, Sorry for the inconvenience. i'll raise PR around 2pm if thats manageable

**Comment by shantanuSakpal** [comment]
@piyushhsainii still working on this?

**Comment by devsargam** [comment]
This is done

**Comment by shantanuSakpal** [comment]
please close the issue then
