### ISSUE TITLE
bug: 404 on track page

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#401]
https://projects.100xdevs.com/tracks/6SbPPXGkG8QKFOTW9BmL/ts-1

@nimit9 probably because of the sign up PRs

**Comment by hkirat** [comment]
works if I navigate from the landing page
but doesnt if I directly go to the link

**Comment by hkirat** [comment]
Try goning to the link in incognito

**Comment by nimit9** [comment]
Working fine on local, also getting 502 now,
Was it giving an error on all tracks?

**Comment by hkirat** [comment]
I've reverted it for now
Was getting a 404 when hitting the link directly

**Comment by Pritam12F** [comment]
@hkirat can I take this up if the issue comes back?

**Comment by SujithThirumalaisamy** [comment]
> @hkirat can I take this up if the issue comes back?

He only reverted the changes. That PR should be worked on IG. The page 3 login pop up.

**Comment by Pritam12F** [comment]
@SujithThirumalaisamy I don't see the issue anymore, how do i recreate it?

**Comment by Pritam12F** [comment]
@SujithThirumalaisamy no i mean the original commit that created this issue. was it to fix some bug or just a feature?

**Comment by SujithThirumalaisamy** [comment]
> @SujithThirumalaisamy no i mean the original commit that created this issue. was it to fix some bug or just a feature?

I was for a feature. To make the user to login after the second slide

**Comment by Pritam12F** [comment]
> > @SujithThirumalaisamy no i mean the original commit that created this issue. was it to fix some bug or just a feature?
> 
> I was for a feature. To make the user to login after the second slide

I see got it
