### ISSUE TITLE
feature: Implemented the Leetcode like heatmap feature for user's submissions

### ISSUE THREAD

**Issue by amanbairagi30** [code100x/daily-code#410]
### **Problem Statement**

Currently, in the daily-code project, users can submit their code solutions similar to the LeetCode platform, and they can view their accepted submissions in their profiles. However, there is a lack of functionality for users to effectively track their accountability and progress over time. This limitation diminishes the user experience and prevents users from setting and achieving goals related to their daily coding practice and along with that if I am not wrong , Harkirart has also mentioned in one of his recent video that he is supposed to build leetcode like features end-to-end.

### **Solution** :
To solve this issue , I have implemented a heatmap feature inspired by platform like LeetCode. This feature provides users with a visual representation of their coding activity over time, allowing them to track their progress, identify patterns, and stay motivated in their coding journey. 
In this version of Heatmap , Users can not only see the entire year once but also can individually see each month according to them .

Below is how the changes looks like : 
![image](https://github.com/code100x/daily-code/assets/118182376/531cef56-518a-44df-aeb4-6e827c39334a)
 
On hovering date box
![image](https://github.com/code100x/daily-code/assets/118182376/84f8d739-238d-4fcd-bca4-66652eeb4536)

**In action :** 

https://github.com/code100x/daily-code/assets/118182376/b144b366-7a23-41ee-a53b-8d5c32ae8cc5

**Comment by ebe25** [comment]
yo @amanbairagi30  that's hella cool bro. GG.

**Comment by amanbairagi30** [comment]
> yo @amanbairagi30  that's hella cool bro. GG.

Thanks bro 🙌

**Comment by AdityaRajThakur** [comment]
that's awesome bro, I like it.

**Comment by DipakKhade** [comment]
Appreciable bro
