### ISSUE TITLE
bug: Move back components to apps/web

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#413]
We have a lot of components in `packages/ui` that are using `apps/web`
This is a circular dependency. We should move these back to ui

**Comment by nimit9** [comment]
Working on this, might be a huge change

**Comment by ShubhamMewara** [comment]
working on it

**Comment by SujithThirumalaisamy** [comment]
> @SujithThirumalaisamy @ShubhamMewara I think you guys have added a lot of components, can you guys coordinate and complete this, Basically all the components will have to be moved to apps/web, only Shadcn components need to be in UI, all the components which use state/recoil logic have to be moved back to apps/web from UI.

#414 Drafted one. Can you please update if you have changes. Not clean I think. Working on hotly on the request changes
