### ISSUE TITLE
bug: Failed to compile during setup

### ISSUE THREAD

**Issue by Vishvsalvi** [code100x/daily-code#422]
**Describe the bug**
![image](https://github.com/code100x/daily-code/assets/82429084/8f55f52d-59ff-4562-adad-390cba220722)

**To Reproduce**
1. After setting up the db run yarn dev or npm run dev
2. See error

**Comment by hxdy-1** [comment]
@Vishvsalvi working fine for me...
didn't get any errors

**Comment by SarfrazAlame** [comment]
it works fine on my machine

**Comment by Vishvsalvi** [comment]
Did you guys use docker or local setup?
