### ISSUE TITLE
bug: Mark as complete not working

### ISSUE THREAD

**Issue by MeerUzairWasHere** [code100x/daily-code#430]
https://github.com/code100x/daily-code/assets/121447358/101189a8-07d1-4d74-a40f-99b1276e3542

**Comment by MeerUzairWasHere** [comment]
this bug is regarding

**Comment by MeerUzairWasHere** [comment]
This bug is regarding app.100xdevs... I able to find the repo of that project ... I don't even know is that repo open source...

**Comment by iharsh02** [comment]
issue realted to cms repo

**Comment by MeerUzairWasHere** [comment]
thanks lol
