### ISSUE TITLE
bug: App bar Alignment

### ISSUE THREAD

**Issue by yash-kh** [code100x/daily-code#432]
App bar Alignment is not consistent and have a lot of alignment issues

1. Run the app
2. Open any slide

App bar should look uniform and should be in a straight line

As you can see here 

All icon here should be aligned:
<img width="1680" alt="Screenshot 2024-05-19 at 2 56 27 PM" src="https://github.com/code100x/daily-code/assets/60394241/7cba6cff-0dfa-4de3-b8e5-d6edf77f0e08">
and here:
<img width="705" alt="Screenshot 2024-05-19 at 2 49 07 PM" src="https://github.com/code100x/daily-code/assets/60394241/99f7e04b-9b51-4d1c-8430-047bfe37bfbe">

App bar could be thin, and the right portion should be in middle:
<img width="1680" alt="Screenshot 2024-05-19 at 2 45 44 PM" src="https://github.com/code100x/daily-code/assets/60394241/0e84c5c4-f003-4c0b-9ec6-dee307043659">

**Comment by Tanishq1604** [comment]
hey, i think i didnt understand the bug , i think u are saying that when at the speicifc width of the screen in the second screenshot these align vertically instead of being horizontal right ?? please correct me if i am wrong
