### ISSUE TITLE
bug: Disable Login Requirement During Development Phase Due to  Authentication Issues and Local Database on the `LessonView`

### ISSUE THREAD

**Issue by SOUMITRO-SAHA** [code100x/daily-code#437]
**Describe the bug**
When users visit https://projects.100xdevs.com/ and browse through the posts, they are required to log in, which is understandable for the production environment. However, during the development phase, this requirement is not practical since the application is running on a local development database. Additionally, the Google login is not functioning correctly in the development setup, likely because the authentication route isn't configured for localhost:3000. It would be beneficial to remove the login requirement during the development phase.

**To Reproduce**
 1. Go to https://projects.100xdevs.com/ without logging in, or use incognito mode.
 2. Open any article.
 3. Navigate to page 2 or beyond.
 4. You will encounter the Login Dialog, even in the development setup.

**Expected behavior**
The login requirement should be disabled during the development phase, as it does not serve a useful purpose.

**Screenshots or GIFs**
![image](https://github.com/code100x/daily-code/assets/68202064/6b62bdd3-0861-429e-842b-cb1d10838072)

**Info (please complete the following information):**

**Additional context**

**Comment by ayesparshh** [comment]
![Screenshot 2024-05-20 145619](https://github.com/code100x/daily-code/assets/96340685/89ee862e-81d7-482a-b45e-13fa3ebf1891)
sorry for offtopic question
im getting this error after running the repo please help, not able to run the code due to this error

**Comment by t007rushi** [comment]
@ayesparshh This happens many times just try 
take latest pull
remove package-lock.json and node_modules 
```
rm -rf node_modules 
rm package-lock.json
```
and 
`npm install`

**Comment by SOUMITRO-SAHA** [comment]
Essentially, `MODULE_NOT_FOUND` indicates an issue with your node_modules. This repository uses yarn, so please use yarn.

If you encounter any issues, follow @t007rushi 's  advice: first, remove `node_modules`, pull the latest updates, and then run `yarn`

**Comment by ayesparshh** [comment]
it did worked thanks @SOUMITRO-SAHA @t007rushi
