### ISSUE TITLE
bug: Frontend Layout issue

### ISSUE THREAD

**Issue by krishna9358** [code100x/daily-code#449]
**Describe the bug**
The content the card shown in the picture is out of the card including the button.

**Expected behavior**
The layout should be responsive so that whole content can be visible in a card for all screen sizes.

**Screenshots or GIFs**
![image](https://github.com/code100x/daily-code/assets/37434769/350b2a45-1619-4c7d-89d7-ccef68c6bc57)

Bigger Screen size view 
![image](https://github.com/code100x/daily-code/assets/37434769/83f28fe5-045e-4a19-9d51-68ba76d2cfdf)

**Comment by punyakrit** [comment]
Already made a pr for this issue #446
