### ISSUE TITLE
bug: Copied message not working

### ISSUE THREAD

**Issue by Chirag-16** [code100x/daily-code#454]
**Describe the bug**
when we click on copy button then  **copied message** not appear.

**To Reproduce**
1. open any slide of dailycode and click on copy button
2. See error

**Info (please complete the following information):**
 - Browser [chrome, safari]

**Comment by Chaitanya1672** [comment]
@Chirag-16 I tried following the instructions, but I was able to copy the code successfully. Could you please specify the exact steps or slides where you encountered issues copying the code?

**Comment by Chirag-16** [comment]
Yes @Chaitanya1672 we was able to copy successfully. but when we click on copy button the **`Copied !!`** message not showing.

**Comment by samrudh3125** [comment]
why am I seeing this when I run code locally
![Screenshot from 2024-06-03 19-27-00](https://github.com/code100x/daily-code/assets/69446481/c97da2d6-ba32-464e-8275-a3c0d09faa5e)
