### ISSUE TITLE
bug: content/command hide behind copy icon

### ISSUE THREAD

**Issue by NegiSushant** [code100x/daily-code#456]
**Describe the bug**
most of the commands/contents are hidden behind the copy button or due to copy button  full command does not seen

**To Reproduce**
1. Go to any topic page
2. See the command/content on code snipet

**Expected behavior**
following three thing can be do:
1. make transparent the copy icon
2. keep distance between content/command and copy icon
3. after click on the copy icon, icon should be change from copy to right tick

**Screenshots or GIFs**
![image](https://github.com/code100x/daily-code/assets/107835408/34704a2d-0eb4-449a-b154-3f768e0a22a1)

![image](https://github.com/code100x/daily-code/assets/107835408/0136d724-7f8d-40a7-891c-ef63563e9b0d)

**Comment by skmanoj322** [comment]
<img width="1065" alt="Screenshot 2024-06-05 at 10 00 06 PM" src="https://github.com/code100x/daily-code/assets/86718126/8a022b85-e791-471b-ab4a-48e918e5c1e2">
<img width="527" alt="Screenshot 2024-06-05 at 9 56 52 PM" src="https://github.com/code100x/daily-code/assets/86718126/7751cd87-3b20-4ec6-95bd-ad2d7ae8e4ef">

**Comment by NegiSushant** [comment]
same thing i also seen in different content pages. may be there is some issues in screen sizes(responsiveness).

**Comment by saket-dev01** [comment]
maybe this version has not been deployed, hence we are still seeing the old copy button
