### ISSUE TITLE
feature: Copy Button on Code block UI/UX update

### ISSUE THREAD

**Issue by kushalnareda** [code100x/daily-code#462]
The copy button hides the code on the code block

**Steps to reproduce**
1. Visit the page with the code block
2. Click on the copy button

<img width="294" alt="Screenshot 2024-06-10 at 5 14 22 PM" src="https://github.com/code100x/daily-code/assets/128476254/440371b9-14f1-4ab2-bf36-3d04f7bb41a7">

**Solution I would like**
- The Copy button does not hide the code.
- Trigger a Code copied message 

https://github.com/code100x/daily-code/assets/128476254/6bd12296-ddf6-4fba-acd5-45714d65c5de

https://github.com/code100x/daily-code/assets/128476254/c4f5d344-cb5d-4a2d-acaa-d5ee4899b0c6

**Comment by Sah-Abhishek** [comment]
The copy button does not provide any feedback that the code is copied. There should be a toast that says "copied" so that person knows that the code did copied.
