### ISSUE TITLE
feature request: Add a 'Continue Learning' button for seamless resumption of learning sessions from saved progress.

### ISSUE THREAD

**Issue by kumarrohitdev** [code100x/daily-code#467]
## Feature Request: Popup Notification for Resuming Learning

**Is your feature request related to a problem? Please describe.**
Many users start learning paths but often leave them incomplete. To address this issue and encourage continuous learning, we propose implementing a solution where users receive a popup upon returning to the website, allowing them to easily navigate back to their last visited page.

**Describe the solution you'd like**
Implement a popup notification upon returning to the website that prompts users to resume from their last visited page, thereby facilitating seamless continuation of their learning journey.

**Describe alternatives you've considered**
We have considered alternatives such as:
- Adding a "Continue Learning" button directly on the interface.
- Integrating a sidebar widget showing recent courses or topics for quick access.

**Additional context**
This feature aims to enhance user motivation and engagement by simplifying the process of resuming learning sessions and reducing the barrier to completing learning paths.

**Comment by kumarrohitdev** [comment]
I am Working on it ..

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@kumarrohitdev can i join you ?

**Comment by kumarrohitdev** [comment]
yes please.

**Comment by kumarrohitdev** [comment]
Hey @devsargam, I want to work on any bug or issue. Could you please guide me on how to get started?
