### ISSUE TITLE
bug: copy button overlaps with code

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#469]
<img width="899" alt="Screenshot 2024-06-15 at 7 47 12 AM" src="https://github.com/code100x/daily-code/assets/8079861/58ea09e3-4841-4916-bb98-3c261334c0fe">

**Comment by ShubhamMewara** [comment]
@hkirat 
Already fixed and merged in #453

**Comment by AyushShivhare79** [comment]
Yes it was already fixed but why it is not showing in projects.100xdevs? @hkirat

**Comment by ShubhamMewara** [comment]
> Yes it was already fixed but why it is not showing in projects.100xdevs? @hkirat

it has not been deployed
