### ISSUE TITLE
feature: Add page navigations at the end of pages |it gets hard to scroll up everytime 

### ISSUE THREAD

**Issue by shravankumar8** [code100x/daily-code#470]
Problem:
I'm encountering an issue where, after completing each page, I need to scroll all the way up to click "Next." This causes a poor user experience.

Solution:
A simple solution would be to add the "Next" and "Prev" buttons from the top navbar to the bottom of the page. This would allow users to navigate easily without scrolling back up.

Alternative Solution:
An alternative solution would be to create a button that, when clicked, moves the user's position to the top of the page. This button would act like a "Scroll to Top" feature.

Additional Context:
I posted an image reference for what needs to be done. Adding this feature could greatly enhance the user experience.
All the best ! happy coding :-)

![Untitled design](https://github.com/code100x/daily-code/assets/129931042/a878fc5e-f4b1-4d92-99c9-180747dc434e)

**Comment by kshaan-ali** [comment]
hey i want to start contribution i think can solve this can you guide me?

**Comment by shravankumar8** [comment]
@kshaan-ali hello Ali , Subham has already opened a pull request solving the issue .
