### ISSUE TITLE
bug: a little typo in track 1 of typecsript 

### ISSUE THREAD

**Issue by MohammadHarish52** [code100x/daily-code#473]
![Screenshot 2024-06-20 022347](https://github.com/code100x/daily-code/assets/109061798/c90b8694-176a-4611-b278-4b7f7aec7675)
"Javascript is a Powerful language" instead of power

wasn't necessary but saw it

**Comment by saket-dev01** [comment]
I think the slides come from another database and it's not a fault in the code.

**Comment by MohammadHarish52** [comment]
hope someone fix it

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
mention @hkirat
