### ISSUE TITLE
bug: Build is failing

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#475]
<img width="927" alt="Screenshot 2024-06-20 at 11 41 16 PM" src="https://github.com/code100x/daily-code/assets/8079861/69574b12-c5e5-401d-8ab7-e4bc0ade3eee">

**Comment by ShubhamMewara** [comment]
###  cannot reproduce the issue.

![Screenshot 2024-06-21 004918](https://github.com/code100x/daily-code/assets/136337515/64b7694e-9abf-4fc1-9488-831b7cc0f0de)

**Comment by SujithThirumalaisamy** [comment]
![image](https://github.com/code100x/daily-code/assets/108384868/45f69313-1976-412f-a554-336bc08b89c9)
Unable to repoduce this issue.
