### ISSUE TITLE
bug: Wrong subtitle

### ISSUE THREAD

**Issue by Yasshu55** [code100x/daily-code#477]
**Describe the bug**
This should be - **Implementing Vertical scaling in Node.js project** instead of horizontal scaling
someone fix this 

![image](https://github.com/code100x/daily-code/assets/95294297/161a873c-7b28-4f0a-bee4-e68269a59ff0)

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
Only @hkirat can change it he has all the control over the notion docs
