### ISSUE TITLE
feature: Link Dailycode tracks with respective pages in app.100xdevs

### ISSUE THREAD

**Issue by shashidhxr** [code100x/daily-code#486]
**Is your feature request related to a problem? Please describe.**
Opening Dailycode tracks seperately and having to navigate to the relevant track is difficult and time consuming.

**Describe the solution you'd like**
Adding clickable blocks alongide lecture videos which will direct to appropriate track in https://projects.100xdevs.com

**Additional Details**
This would be very useful to build projects without having to go through the entire lecture and can also be useful in instilling the prerequisites.

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
but during watching lectures there is a button slides through which you can directly come to the respective slide....
If your suggestion is different ..can you elaborate it please
@shashidhxr

**Comment by shashidhxr** [comment]
Actually you are right. I got confused as initally slides were different and slides button took us to the actual slides used in the video. Now Dailycode tracks are used as slides.
