### ISSUE TITLE
Create aliases for the imports to omit long import statements (dev issue not end user's)

### ISSUE THREAD

**Issue by i-amansharma07** [code100x/daily-code#487]
**Problem:**
In the Screen Shot below we have a very long import statement which disrupts the code appearance and also make importing components harder which can be done relatively easy manner.

![code](https://github.com/code100x/daily-code/assets/91537129/9f5f6223-3982-43d0-b945-7f909bd984ec)

Can be seen in these files as well : 

![Screenshot from 2024-07-07 23-36-36](https://github.com/code100x/daily-code/assets/91537129/13d5eb9d-03bc-4cdf-ac27-34ae167da1e4)

**Solution**
We can use path aliasing like `@components/AppbarClient` there are some alias already present inside _next.config.js_ and we can describe some more and use it as a standard to bring uniformity in the code base.

correct imports examples : 

![code](https://github.com/code100x/daily-code/assets/91537129/4d9dd168-d492-44c3-9bcd-e2fff5d16814)

**Comment by i-amansharma07** [comment]
> Hi, I'd like to work on this issue. Could you please assign it to me?

Hey Vishwas i don't have permissions to assign tasks, you can complete your work and raise a PR, thanks for picking this up.

**Comment by vishwas-babar** [comment]
Ok I will work on that then raise a pr

**Comment by S007K** [comment]
To create aliases in a React codebase, particularly in a Next.js project, you can use path aliasing for import statements. This can be achieved by making modifications to the next.config.js file and then using the defined aliases in the codebase.

Here are the steps to create aliases in a React codebase, specifically in a Next.js project:

Modify next.config.js: In the root of your Next.js project, create or open the next.config.js file. If it doesn't exist, create this file at the root of your project.

Inside next.config.js, you can use the resolve.alias property to define your path aliases. Here's an example of how to define aliases for commonly used paths:
```// next.config.js
const path = require('path');

module.exports = {
  webpack: (config, options) => {
    config.resolve.alias['@components'] = path.join(__dirname, 'components');
    config.resolve.alias['@styles'] = path.join(__dirname, 'styles');
    // Add more aliases as needed
    return config;
  },
};```

**Comment by S007K** [comment]
Using the Aliases in Code: After defining the aliases in next.config.js, you can now use these aliases in your import statements throughout your codebase. For example, if you defined an alias for '@components', you can import components like this:

```javascript
import AppbarClient from '@components/AppbarClient';
```

**Comment by S007K** [comment]
i hope it has answered your issue

**Comment by S007K** [comment]
i have also raised the PR #500 , on merging it resolved this issue.
Happy coding 👍

**Comment by i-amansharma07** [comment]
Yes but can you also use these aliases and update the PR?

**Comment by S007K** [comment]
yes! thanks for updating me
