### ISSUE TITLE
Cache page requests

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#490]
Esp here - https://github.com/code100x/daily-code/blob/main/apps/web/components/utils.tsx#L11

Cache for 30 mins

In memory cache is fine

**Comment by Ameerjafar** [comment]
@hkirat can i pick up this one sir?

**Comment by dishant440** [comment]
working on it

**Comment by Ameerjafar** [comment]
@hkirat i have made the pr can you please review that.

**Comment by Ameerjafar** [comment]
@hkirat can i add cache for every function or getproblem function is enough?

**Comment by monish-mukhari** [comment]
@Ameerjafar for every get may be

**Comment by Ameerjafar** [comment]
@monish-mukhari  then why he mentioned from that particular line only?

**Comment by monish-mukhari** [comment]
other may me SSG
