### ISSUE TITLE
feature: Home Button added to BlogAppBar

### ISSUE THREAD

**Issue by tillu002** [code100x/daily-code#493]
**Is your feature request related to a problem? Please describe.**
Whenever we are viewing a specific track it is difficult to see other tracks as there is no dedicated button to go to home where all the tracks are viewed.

![Screenshot 2024-07-11 235410](https://github.com/code100x/daily-code/assets/121672097/cc73f817-8b93-4aed-b3e8-a3da9e064d80)

**Describe the solution you'd like**
By adding a small Home button in the BlogAppBar which on clicking takes back to the home page

**Comment by Debajit-Paul** [comment]
@tillu002 You can click on the DailyCode logo, which will redirect you to home, most websites have this UI/UX

**Comment by tillu002** [comment]
Ohh but it will be easy for anyone to use a visual button. Anyway thanks for the feedback

**Comment by Pushh02** [comment]
hey, can you assign me this issue? I can implement it.

**Comment by Inayat27** [comment]
@tillu002  as per the suggestion of @Debajit-Paul , i think he right and instead of adding button , we can improve UI something like this .
<img width="960" alt="image" src="https://github.com/user-attachments/assets/807830d3-d1c2-44f6-9e27-d27c9c719fc3">

If it is ok then can i implement.

**Comment by S007K** [comment]
@Inayat27 I think you should make a PR , it will definitely looks good

**Comment by S007K** [comment]
also add some margin-x, it will give margin from left and right

**Comment by Inayat27** [comment]
@S007K Thanks for suggestion
