### ISSUE TITLE
When using the Download option for a particular topic, generated PDF is NOT including the images and page break is not consistent

### ISSUE THREAD

**Issue by skodavalla** [code100x/daily-code#494]
**Describe the bug**
When using the Download option for a particular topic, generated PDF is NOT including the images and page break is not consistent

**To Reproduce**
1. On the daily code website (https://projects.100xdevs.com/) select a topic by using the Explore option
2. Once the topic loads, select the Download option in the top right hand corner
3. Wait for the PDF to be generated
4. Once PDF is generated, we can see that the images are NOT present and pagination is incorrect

**Expected behavior**
Once PDF is generated, we MUST see that the images and pagination should be correct 
**Screenshots or GIFs**

**Info (please complete the following information):**
 - Browser Chrome 
 - Version 126.0.6478.127 (Official Build) (64-bit)

**Additional context**

**Comment by dishant440** [comment]
> **Describe the bug** When using the Download option for a particular topic, generated PDF is NOT including the images and page break is not consistent
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. On the daily code website (https://projects.100xdevs.com/) select a topic by using the Explore option
> 2. Once the topic loads, select the Download option in the top right hand corner
> 3. Wait for the PDF to be generated
> 4. Once PDF is generated, we can see that the images are NOT present and pagination is incorrect
> 
> **Expected behavior** Once PDF is generated, we MUST see that the images and pagination should be correct **Screenshots or GIFs** If applicable, add screenshots to help explain your problem.
> 
> **Info (please complete the following information):**
> 
> * Browser Chrome
> * Version 126.0.6478.127 (Official Build) (64-bit)
> 
> **Additional context** Add any other context about the problem here.

@skodavalla when you click on download  button on the slide and the pdf preview window opens just go to more settings and select background graphics

**Comment by skodavalla** [comment]
Yeah I did check that. However still some images and pagination is NOT consistent. Please see attachement.
[KafkaIncompleteDailyCode.pdf](https://github.com/user-attachments/files/16283976/KafkaIncompleteDailyCode.pdf)
