### ISSUE TITLE
should have a "jump to page number" feature. 

### ISSUE THREAD

**Issue by PranavKumar20** [code100x/daily-code#50]
website currently only have "previous" and "next" page option, in case if anyone want to go to any specific page the need to click next of previous as per the page, there should have a page number input box that should accept the page number and forward user to that page.

pros:
1) easy to get through the content.
2) decrease the number of reloads( if a user is on page 1 and want to go to page 30 then the user will have to press "next" 29 times, which will reload the website 29 times, whereas it can be done in single click only if it have jump to page feature)

**Comment by hkirat** [comment]
We probably need a Dropdown where user can see all the lessons and then click on one rather than a number input @kaustavsarkar14 
No one's going to type a number, they wont know what page it leads to
