### ISSUE TITLE
bug: code component does not wrap the content

### ISSUE THREAD

**Issue by Not-Sarthak** [code100x/daily-code#502]
**Describe the bug**
The code snippet within the markdown doesn't wrap properly, which negatively impacts responsiveness.

**To Reproduce**

https://github.com/user-attachments/assets/94c078d8-6a15-4049-8e1b-9d7a42a5db99

**Expected behavior**
The code snippet should wrap its content to fit the container width.

**Info (please complete the following information):**
 - Chrome

**Additional Context**
This issue affects the readability and responsiveness of code blocks, especially on smaller screens or when the code lines are long.

**Comment by rohitt-gupta** [comment]
Hi Maintainer,
I am working on it!
