### ISSUE TITLE
Add different section for Cohort 3

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#504]
We need a cleaner slate for cohort 3 slides
Specifically we need three sections
1. Devops
2. Web dev
3. Web3

User should probably be able to select these in the topbar

**Comment by ShubhamMewara** [comment]
working on it.

**Comment by keshav-exe** [comment]
@ShubhamMewara can i join you here?

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@ShubhamMewara i would also love to join

**Comment by NawabSheik** [comment]
I am working upon this if anyone is interested
