### ISSUE TITLE
bug: copy button not working when clicked

### ISSUE THREAD

**Issue by toufiqfarhan0** [code100x/daily-code#509]
Copy button is not working when clicked and not coping the code 

https://github.com/user-attachments/assets/abb8d155-b5c0-4da7-9333-d89e8cbaf01e

Expected behavior:
Copy the code when copy button is clicked

**Comment by iharsh02** [comment]
its working you can check by pasting somewhere

**Comment by ramnaresh8** [comment]
yes, the issue is the animation isn't working but it is getting copied, check your clipboard using win + v if on windows or try pasting in case of mac

**Comment by devsargam** [comment]
@ramnaresh8 do you want to work on this?

**Comment by ramnaresh8** [comment]
> @ramnaresh8 do you want to work on this?

Yes, please assign it to me.

**Comment by toffee-k21** [comment]
it is already solved in the current repo

**Comment by DivyeshPatel007** [comment]
@devsargam  can you assign me this issue  i have done with better UI

**Comment by toufiqfarhan0** [comment]
Is it solved?

**Comment by DivyeshPatel007** [comment]
Yes

**Comment by toufiqfarhan0** [comment]
> @devsargam I would like to work on this.

this is solved in current repo

**Comment by toufiqfarhan0** [comment]
> @ramnaresh8 do you want to work on this?



this issue has be solved in current repo but not updated.

**Comment by ramnaresh8** [comment]
> > @ramnaresh8 do you want to work on this?
> 
> this issue has be solved in current repo but not updated.

Okay,
