### ISSUE TITLE
bug: Source code not match the existing deployed project

### ISSUE THREAD

**Issue by toffee-k21** [code100x/daily-code#510]
**Describe the bug**
The GitHub source code does not match the deployed project 

**To Reproduce**
1. Setup locally 
2. Compare the UI of locally set project and the deployed one

**Expected behavior**
Should have synced with the codebase that is on GitHub

**Screenshots or GIFs**
![Screenshot 2024-08-04 145340](https://github.com/user-attachments/assets/a65c7fa4-9d8c-4240-a7e0-e1c61bea667b)
![Screenshot 2024-08-04 145347](https://github.com/user-attachments/assets/220dca36-f6fd-4304-a467-f4377246cb29)

**Additional context**
In above images, you can compare the copy button for example
This is creating issues for the user and contributor, they are creating issues that are not there in the source code, & this leads to confusion

**Comment by Pheewww** [comment]
i guess maybe they are using the most stable version in prod and not picking from each merging that happens.

**Comment by sand-storm-17** [comment]
Yeah, the new JavaScript101 learning path is missing along with other learning paths. 

![Screenshot 2024-08-04 220036](https://github.com/user-attachments/assets/7f89774d-89e3-482f-91b2-b79703434421)
![Screenshot 2024-08-04 220051](https://github.com/user-attachments/assets/ee12135f-f76d-4737-a8a6-313526e5d0dc)

Please push the latest version in this repo
