### ISSUE TITLE
bug: Fix numbering of the slides

### ISSUE THREAD

**Issue by Chirag-18** [code100x/daily-code#513]
In "Javascript 101" track numbering of slides is wrong in "Jump To" button.

It should be :

1- Did you code yesterday?
2- Javascript - The Basics
3- Properties of JS
4- Syntax of Javascript
5- Complex types

![image](https://github.com/user-attachments/assets/a1c01aa6-16ee-4be3-997b-dfeb9cd8f890)

**Comment by yagnangg333** [comment]
I set a site locally but this page is not visible locally. what is a reason behind it??

**Comment by ramnaresh8** [comment]
> I set a site locally but this page is not visible locally. what is a reason behind it??

Because the data is being fetched from the database, you might won't see this slide but the test tracks on seeding the database.

**Comment by yagnangg333** [comment]
> > I set a site locally but this page is not visible locally. what is a reason behind it??
> 
> Because the data is being fetched from the database, you might won't see this slide but the test tracks on seeding the database.

So can i solve this issue?? because in local site every slides have a perfect number. so can I?

**Comment by yagnangg333** [comment]
@XprabhatX  Thank you for details explanation. I kind of new for open source so thank you.

**Comment by kunal-v2** [comment]
the site is not running locally can anyone help?

**Comment by Chirag-18** [comment]
Hey @devsargam, can you please explain why you have changed it to completed ? As the site is not reflecting the correct order till now.

**Comment by devsargam** [comment]
@Chirag-18 It's a database level edit. We can not do anything about that
