### ISSUE TITLE
Remove the code execution part that exists in algo-area from daily-code

### ISSUE THREAD

**Issue by devsargam** [code100x/daily-code#518]
### Intro
Currently, we have [algo-arena](https://github.com/code100x/algorithmic-arena/) which is the codeforces like platform for 100xdevs. Prior to that we had that portion of code in daily-code.

### Expected
As of now, daily-code's sole purpose is to serve notes + slides for anyone. Any portion of code that belongs to the code-execution + submission + adding of problems is not required. Please remove it.

**Comment by Saurabhchaddha6** [comment]
can i work on this?
