### ISSUE TITLE
bug: In Rust Bootcamp The Variables section is not responsive

### ISSUE THREAD

**Issue by Puskar-Roy** [code100x/daily-code#522]
**Describe the bug**
In the Rust Bootcamp, the "Variables" section is not responsive. When viewed on smaller screens or devices, the layout breaks, making it difficult to read and interact with the content.

**To Reproduce**
1. Do something
2. See error
3. Open the Rust Bootcamp in a browser.
4. Navigate to the "Variables" section.
5. Resize the browser window or open the page on a mobile device.
6. Observe that the content is not responsive and elements overlap or are misaligned.

**Expected behavior**
The "Variables" section should be responsive and adjust to different screen sizes without breaking the layout. All content should be easily readable and interactable on any device.

**Screenshots or GIFs**
![Screenshot_2024-08-10_02_54_45](https://github.com/user-attachments/assets/2143968e-00bc-4926-a8bb-7d11a13d1387)

**Info (please complete the following information):**
 - Browser [e.g. chrome, safari] - Brave

**Additional context**

**Comment by devsargam** [comment]
Hey @Puskar-Roy, thank you for raising this issue but it has already been resolved in #506

**Comment by IVEWOR** [comment]
a non related question do we have classes for rust in th cohort 3?

**Comment by devsargam** [comment]
@IVEWOR yeah for the web3 cohort

**Comment by IVEWOR** [comment]
@devsargam If I'm not wrong these classes have not started yet? Or they are in offline mode? We just covered public and private keys topic.

**Comment by devsargam** [comment]
@IVEWOR yep they have not been stared for the rust bootcamp. We are just going through some basic theoritical cryptography stuff

**Comment by IVEWOR** [comment]
@devsargam got it. Thanks man!!
