### ISSUE TITLE
bug: Slide and Navigation slide numbering mismatch for javascript 101

### ISSUE THREAD

**Issue by Arghyahub** [code100x/daily-code#523]
**Describe the bug**
In recent Harkirat's video the javascript 101 page's slide and slide numbering mismatched.

**To Reproduce**
1. Javascipt 101
2. Slide numbering starts from 3/5

**Expected behavior**
Slide numbering should start from 1/5

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/15e2acca-87b3-4146-af2d-52fd99a72762)

**Info (please complete the following information):**
 - Chrome

**Comment by Arghyahub** [comment]
I wanted to solve it myself, I cloned the repo and seeded the DB but the javascript 101 page data is not available.
I asked the TA on how I could get the latest data he suggested to talk to the maintainers.

Can anyone help?

**Comment by devsargam** [comment]
Hey @Arghyahub, appreciate your enthusiasm trying to solve the problem. Unfortunately it is the ordering problem with the production database that daily-code uses. Can't be solved without have it. 
Closing
