### ISSUE TITLE
feature: copy button must show copied after click

### ISSUE THREAD

**Issue by RithendSushanth** [code100x/daily-code#524]
when clicked on copy button copied must be shown.

**Additional context**
![image](https://github.com/user-attachments/assets/a0b6737e-25a8-4219-9416-ab40d44887d8)

**Comment by dhirajudhani** [comment]
@RithendSushanth I have already solved this issue and created a pr yesterday itself  for it can you please review and let me know is changes i have to make or not

**Comment by NithinJ-17** [comment]
@dhirajudhani Ouch! 👍

**Comment by devsargam** [comment]
it's done in the code. Just need to deploy it to prod
