### ISSUE TITLE
feature: The prev and next button should be at the bottom of the page

### ISSUE THREAD

**Issue by Aishwarya7902** [code100x/daily-code#527]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NithinJ-17** [comment]
@Aishwarya7902 Can i take up this issue?

**Comment by devsargam** [comment]
And why should that be the case? What is the main problem it solves. Can you explain a bit regarding the issue

**Comment by Aishwarya7902** [comment]
The problem with next on top is that ...lets say i began reading a page , then I will scroll down the page ...then obviously I would want to go to next page , but if I have to scroll above to go to next page , then I guess it's a bad user experience.

Thanks.
________________________________

**Comment by devsargam** [comment]
Thank you. It should be better experience after 532 gets merged
