### ISSUE TITLE
bug: Below Footer there is a SVG show there

### ISSUE THREAD

**Issue by Rahul-Bhati** [code100x/daily-code#530]
**Describe the bug**

**To Reproduce**
1. go to https://projects.100xdevs.com/
2. Go to below in this page

**Screenshots or GIFs**
[
![357482358-6737a11c-2092-456e-9bc3-7e93113a9adf](https://github.com/user-attachments/assets/1c25c56a-fa76-41c2-ac2f-73d1f6ecd4f2)
](url)

**Comment by thecurioussailor** [comment]
This issue is not in development.

**Comment by devsargam** [comment]
Known issue should be fixed soon. thanks for raising the issue.
