### ISSUE TITLE
bug: Docker compose watch not working 

### ISSUE THREAD

**Issue by Dhruveren** [code100x/daily-code#533]
I am having issues running the docker-compose watch, as instructed in the readme.

**Comment by Dheeraj431** [comment]
what is the problem you are facing, please explain.

**Comment by Dhruveren** [comment]
> what is the problem you are facing, please explain.
The normal setup of the project is fine, but with docker, it is creating issues. It might be my system issue or might not be. 
<img width="746" alt="Screenshot 2024-08-16 at 6 57 21 PM" src="https://github.com/user-attachments/assets/13ed0c05-f52b-4484-bb17-32074ae55153">

**Comment by devsargam** [comment]
@Dhruveren thanks for letting us know. Please proceed with the mannual procedure for development as of now
