### ISSUE TITLE
feature: When clicked on copy button the button should change to copied!

### ISSUE THREAD

**Issue by sreecharan-desu** [code100x/daily-code#534]
## 🚀 Copy Button Enhancement

When users click the "Copy" button, it instantly transforms into a "Copied!" button, providing immediate feedback and improving the overall user experience. This small but impactful feature ensures users know their action was successful, making the interaction seamless and more intuitive.

## Here is the video descroption of the problem 

[copy-button-feature-request.webm](https://github.com/user-attachments/assets/98a8261f-ad27-4c7b-926c-5103b72b21b2)

**Comment by Dheeraj431** [comment]
this is same as #524, there is a PR raised to solve this.

**Comment by devsargam** [comment]
same as above
