### ISSUE TITLE
feature: Course topics overflowing div & need for separate sections for Cohort 2 and Cohort 3

### ISSUE THREAD

**Issue by Sid20rathi** [code100x/daily-code#535]
**There are two issues observed on the site:**

Course Topics Overflowing Div:
The course topics are currently overflowing out of their designated div, causing layout issues. This affects the overall user experience as the content is not properly contained within its boundaries.

Separate Sections for Cohort 2 and Cohort 3:
It would be beneficial to create two distinct sections for Cohort 2 and Cohort 3 on the site. Each section should clearly display the topics covered for that specific cohort. This would enhance organisation and clarity, allowing users to easily navigate and find the relevant content for their cohort.

**Request:**
Can I start working on these issues and submit a pull request with the proposed changes?
![Screenshot 2024-08-18 at 3 54 52 PM](https://github.com/user-attachments/assets/1eb240b2-e50d-4a58-9758-caaa647eb0d7)

**Comment by devsargam** [comment]
Should be fixed
