### ISSUE TITLE
bug:The Dailycode's Search Bar was not working 

### ISSUE THREAD

**Issue by thamarai-titan** [code100x/daily-code#536]
<img width="1280" alt="Screenshot 2024-08-18 at 6 57 12 PM" src="https://github.com/user-attachments/assets/924cba16-6ea4-4eaf-ae7f-a376b4c06c5d">

Title: Search Bar Does Not Return Results

To Reproduce :

- Open the website in a browser (e.g., Chrome).
- Navigate to the Learning Paths section.
- Click on the search bar at the top.
- Type any query into the search bar (e.g., "types").
- Observe that no results are displayed, and the search functionality does not work.

Expected behavior

- The search bar should return relevant results based on the input query.

Browser: Chrome

Additional context

This issue occurs consistently across different queries. The rest of the site appears to function normally.

**Comment by devsargam** [comment]
Hi, thanks for pointing this out. I will check and inform the team

**Comment by toufiqfarhan0** [comment]
This is because the Google API got expired!

**Comment by devsargam** [comment]
Should be fixed when #576 has a pr
