### ISSUE TITLE
bug: Search Functionality and Tab Bar overflow

### ISSUE THREAD

**Issue by DeepanshuMishraa** [code100x/daily-code#537]
Title: Search Functionality Inoperative and Tab Bar UI Overflow Issues

Steps to Reproduce:
1. Navigate to the live site.
2. On the homepage, observe the tab bar in the Learning Paths section overflowing its container.
3. Click on the search bar at the top of the page.
4. Attempt to search for any query; the results will not display.

Expected Behavior:
1. The UI should be responsive and properly formatted for all screen sizes, without overflow issues.
2. The search bar should function correctly, displaying relevant results for user queries.

Actual Behavior:
1. The tab bar in the Learning Paths section overflows its container.
2. The search functionality is non-responsive, failing to display results for any query.

Screenshots:
![image](https://github.com/user-attachments/assets/e7a0b9f4-a609-4610-b0b4-1e3e09b8eba1)
![image](https://github.com/user-attachments/assets/2785a9dd-3cf0-4b1e-8cfc-550259c3e29d)

- Browser: Google Chrome

**Comment by DeepanshuMishraa** [comment]
Can i take this issue?

**Comment by divu777** [comment]
I think the error with the search Functionality is serverside error according to me as i did also check with the recent merges and files related to search hasn't been change , ping me if i am wrong about that ✌️ and yes i am also seeing issue with the tabBar

**Comment by devsargam** [comment]
Yes, I also think it's a server side issue. Thanks you guys for this issue

**Comment by vanshavenger** [comment]
@devsargam  the Ui on the repo when we clone is different from the production Ui, as was checking the overflow issue

**Comment by vanshavenger** [comment]
<img width="1079" alt="Screenshot 2024-08-18 at 9 09 37 PM" src="https://github.com/user-attachments/assets/1f394cc3-cb6a-4620-9253-986e3c1ea6ca">

Search functionality error on dev

**Comment by jasspreetbawa** [comment]
@devsargam bro please tell about this.
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/9266dcda-0457-4842-8523-d03eade2187e">

**Comment by Smnthjm08** [comment]
@devsargam  is this issue still open to work??

**Comment by devsargam** [comment]
Should be fixed when https://github.com/code100x/daily-code/issues/576 has a pr
