### ISSUE TITLE
bug: Pagination option present in both top and bottom

### ISSUE THREAD

**Issue by DeepanshuMishraa** [code100x/daily-code#540]
Title: The Pagination button is both on the appbar as well in the bottom of a particular track

1. Open a particular track and scroll to bottom of it

**Expected behavior**
Pagination option should only be either on top or bottom

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/47431a97-fa12-4d8b-942d-4e75b38f72d8)

 - Browser : Chrome

**Additional context**
I don't know if it's intentional but there should be only one option for pagination either on the top or bottom

**Comment by karthik-nair-20** [comment]
hi @DeepanshuMishraa ,[Pagination button at bottom] change I can suggest here in when we arrive at the bottom of track the top pagination can be hidden.

**Comment by DeepanshuMishraa** [comment]
Good point, but UX-wise, having two pagination buttons isn't good I guess. We can scroll back up to paginate, so one button is enough. Multiple buttons can add clutter and redundancy.

**Comment by devsargam** [comment]
It was intentional guys. I forgot the reason. Would love if you can get a pr with something good.

**Comment by DeepanshuMishraa** [comment]
oh , got it i thought it was some kind of mistake

**Comment by keshav-exe** [comment]
@devsargam this is issue is resolved in my PR

**Comment by devsargam** [comment]
Thanks for clarifying @keshav-exe

**Comment by devsargam** [comment]
Fixed
