### ISSUE TITLE
Bug: On clicking on copy code icon we should get notified "copied" which is missing

### ISSUE THREAD

**Issue by thecurioussailor** [code100x/daily-code#541]
**Describe the bug**
On clicking the copy code icon, we should be notified that " copied " is missing.

**To Reproduce**
1. Go to any track that has a Code Snippet.
2. Click the top-right corner "copy icon". 

**Expected behavior**
When clicked on the copy icon, it should notify text like "copied" to the users.

**Screenshots or GIFs**

Normally:
![image](https://github.com/user-attachments/assets/f396c2d9-692a-461c-bbb5-4441cef3c567)

After clicking on the copy icon:
![image](https://github.com/user-attachments/assets/031f7550-bb17-4be8-8f87-4fca4aa1db4b)

Expected behavior on clicking the copy icon:
![image](https://github.com/user-attachments/assets/814d04e6-08bd-42f8-9db8-5f4a98726f0b)

**Info (please complete the following information):**
 - Browser [Chrome]
 - Version [127.0.6533.100 (Official Build) (64-bit)]

**Additional context**
This issue is visible in development only.

**Comment by thecurioussailor** [comment]
@devsargam Please assign me this issue. I am working on it.

**Comment by thecurioussailor** [comment]
@devsargam PR #543 fixes this issue.

**Comment by devsargam** [comment]
Done
