### ISSUE TITLE
bug: Cohort 3 Web Dev section is going out from Navbar

### ISSUE THREAD

**Issue by vishalmeena2211** [code100x/daily-code#544]
![Screenshot (454)](https://github.com/user-attachments/assets/f513f7c9-cb60-4301-b40b-e5fb8c195d93)
The "Cohort 3 Web Dev" section in the Navbar is overflowing and not fitting properly within its container. This issue likely stems from insufficient space within the Navbar, causing the content to extend beyond its intended boundaries. Adjustments are needed to ensure that the Navbar can accommodate all items without overflow.

**Comment by shekhtausif8090** [comment]
Please remove this tailwind property w-2/3 on parent div then your go to go 
checkout this image https://github.com/user-attachments/assets/6ef12678-3319-4759-8f34-cd54f65844c1

**Comment by yaswanth6610** [comment]
can we increase the nav-bar width? we have space on the left..

**Comment by Allan2000-Git** [comment]
Better to increase the horizontal width

**Comment by vishalmeena2211** [comment]
Will be fixed in upcoming pull requests
