### ISSUE TITLE
feature: Create custo renderer for everything that comes from notion

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#549]
Add custom renderers for
1. headings, 
2. text blocks
So they look slightly prettier than what it looks like right now
<img width="1668" alt="Screenshot 2024-08-20 at 12 08 52 PM" src="https://github.com/user-attachments/assets/ba8b0aab-c6a2-4e71-bd15-9d57d1b19e6a">

**Comment by devsargam** [comment]
Issue up for grasp
If you are feeling like working on this pls raise a pr after #522

**Comment by SujithThirumalaisamy** [comment]
Happy to work on this!

**Comment by ItsFlash10** [comment]
Can I pick this up?

**Comment by svgnix** [comment]
Working on it!!!

**Comment by swaparup36** [comment]
Can I start working on it? @devsargam

**Comment by ItsFlash10** [comment]
@devsargam can you please help let us know what change exactly is being expected here since it's already being formatted according to Notion's format?
Was looking into the code and have refactored and fixed CodeBlock code as there were multiple scrollbars in some scenarios and also the heading of the page was being clipped by the header:

<img width="720" alt="Screenshot 2024-08-20 at 9 29 14 PM (2)" src="https://github.com/user-attachments/assets/871b7029-8fc8-4a0c-91f7-905c811a87f7">


<img width="720" alt="Screenshot 2024-08-20 at 9 22 09 PM (2)" src="https://github.com/user-attachments/assets/f9c65702-64ed-4bcd-a17c-a1ff0007cc6e">

**Comment by rushabhcodes** [comment]
Working on it

**Comment by AshrithSathu** [comment]
Feature added can be verified once by maintainer and be fixed @hkirat @devsargam

**Comment by vekariaayush04** [comment]
<img width="947" alt="ss1" src="https://github.com/user-attachments/assets/7bbb0f02-908d-4190-8bd2-dde37ae9b3ee">
<img width="915" alt="ss2" src="https://github.com/user-attachments/assets/d66a005e-3c3d-4ae7-a380-ddfae6230cc6">

I tried to do change it using vanila css , as there is no option for textBlocks in react-notion-x .
check it out @devsargam 
should i raise PR?

**Comment by AyushShivhare79** [comment]
@hkirat Hey check this hope it's what you wanted.

**Comment by ItsFlash10** [comment]
> @devsargam can you please help let us know what change exactly is being expected here since it's already being formatted according to Notion's format? Was looking into the code and have refactored and fixed CodeBlock code as there were multiple scrollbars in some scenarios and also the heading of the page was being clipped by the header:
> 
> <img alt="Screenshot 2024-08-20 at 9 29 14 PM (2)" width="720" src="https://private-user-images.githubusercontent.com/57027429/359556347-871b7029-8fc8-4a0c-91f7-905c811a87f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxOTExMzgsIm5iZiI6MTcyNDE5MDgzOCwicGF0aCI6Ii81NzAyNzQyOS8zNTk1NTYzNDctODcxYjcwMjktOGZjOC00YTBjLTkxZjctOTA1YzgxMWE4N2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDIxNTM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxOTM3OGNjNWU1MmMyMDMyMDgyMTNmMmE1MjZkZmIwYTUxMGQ0ODhiNDRlOGI5YTg2NGNhZTM1ZDEzMDI1MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dJJ9UAsz3f1AAQdQe-fQCP3eF2B8W_6gCXcesJCTkjQ"> <img alt="Screenshot 2024-08-20 at 9 22 09 PM (2)" width="720" src="https://private-user-images.githubusercontent.com/57027429/359552748-f9c65702-64ed-4bcd-a17c-a1ff0007cc6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxOTExMzgsIm5iZiI6MTcyNDE5MDgzOCwicGF0aCI6Ii81NzAyNzQyOS8zNTk1NTI3NDgtZjljNjU3MDItNjRlZC00YmNkLWExN2MtYTFmZjAwMDdjYzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDIxNTM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5N2NkNTc3YWYzYzcxMzZiNjQwYTc3ZDFiY2VlMjNiMGVhOGFiMmE0ZWRkN2NhNTg1ZTg3YjFlY2NkOTdjMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FsbuCT0zUWYPw2H2DkmP9EUsqwjcGi3Zj8oAgZbIqks">
> **PS: I have to PR ready which I have created from #532 code's branch as you mentioned. @devsargam please assign it to me so that I can raise a PR for the same.**
> 
> Edit1: Just made some changes after watching [this](https://www.youtube.com/watch?v=GCyVFRMVlPo) which was posted today where he explained what was required exactly.
> 
>  themeChange.mp4

Implemented the following:

- Change the theme of NotionRenderer in compliance with the app theme.
- Refactored the code and made it cleaner for CodeBlock.
- Fixed the copy button and added a copied message upon clicking on it.

@devsargam please assign this issue if it fits the requirement so that I can raise the PR post UI changes PR is merged.
CC: @hkirat
