### ISSUE TITLE
bug: Searching functionality is not working properly

### ISSUE THREAD

**Issue by AbhiDiva96** [code100x/daily-code#556]
![Screenshot (330)](https://github.com/user-attachments/assets/42cf9f66-f0a8-4301-a079-036b625712ba)

Searching functionality is not actually working. I have typed lots but not responding.

**Comment by hkirat** [comment]
yeah I think an api key has expired
cc @devsargam

**Comment by iamlikeaproforyou** [comment]
can anyone please work on this issue fast @hkirat @devsargam 
![image](https://github.com/user-attachments/assets/abd5d61e-4b5d-4808-9941-3e1fecf3bb96)

**Comment by devsargam** [comment]
Should be fixed when https://github.com/code100x/daily-code/issues/576 has a pr

**Comment by AbhiDiva96** [comment]
I would like to work on this can you assign me @devsargam
