### ISSUE TITLE
bug: Next button bug in Daily code slides website.

### ISSUE THREAD

**Issue by 2003nayan** [code100x/daily-code#557]
**Description**
Website link: (https://projects.100xdevs.com/tracks/promises-async-await/Promises-and-async--await-1)
When clicked on the next slide, sometimes it is heading to the 3rd one. And happened a couple of times. 

**To Reproduce**
(I did not understand exactly what to mention in here)

**Expected behavior**
When the next button is clicked, it should head to the next slide, not the third slide respectively. 

**Screenshots or GIFs**
![Screenshot (261)](https://github.com/user-attachments/assets/208606c1-d921-43b7-8352-693934fb7bd6)
![Screenshot (262)](https://github.com/user-attachments/assets/b2e4b95a-b3d4-4c1b-b0e2-e031d8090494)

**Info (please complete the following information):**
 - Browser - Chrome
 - Version 127.0.6533.120

**Additional context**

**Comment by Surajsuthar** [comment]
it works proper !!

**Comment by Shahbaz-1696** [comment]
Works fine locally

**Comment by devsargam** [comment]
Doesn't seem like a issue to me. Closing
