### ISSUE TITLE
bug: here some text out of box

### ISSUE THREAD

**Issue by moteeullahazmi** [code100x/daily-code#558]
![image](https://github.com/user-attachments/assets/1228659c-3234-44a0-96d5-3eb534fb3b6d)

**Comment by Surajsuthar** [comment]
It's server side issue ig, locally it's work fine

**Comment by 4kshi7** [comment]
yeah it seems to be a server side issue

**Comment by devsargam** [comment]
Yep, as @4kshi7 & @Surajsuthar said. It's a server side bug
