### ISSUE TITLE
bug: able to view/download the content while begin unauthenticated by pressing download button

### ISSUE THREAD

**Issue by karthikeyaspace** [code100x/daily-code#562]
**Describe the bug**
while logged out, the user was not able to see after 2nd page of any content, but was able to download the entire content by clicking the download button

**To Reproduce**
1. log out of projects.100xdevs.com
2. select any course material
3. click download on top right

**Expected behavior**
shall redirect to https://projects.100xdevs.com/pdf/* page and download content

**Comment by devsargam** [comment]
Can verify. We should add auth to /pdf endpoint
