### ISSUE TITLE
bug: Content overflowing out of the navbar in the learning paths section

### ISSUE THREAD

**Issue by GeeekySouro003** [code100x/daily-code#566]
I have encountered an issue on the Learning Paths page where content is overflowing from the navbar, causing a misalignment and affecting the overall page layout. This bug makes it difficult to navigate through the sections efficiently, especially on smaller screens or when resizing the browser window.

Here is the image for reference :-
![image](https://github.com/user-attachments/assets/0cb31def-81d8-4c5d-8220-a46d8bbca7a9)

**Comment by Sidd-013** [comment]
[https://github.com/code100x/daily-code/pull/571](url)

**Comment by Sidd-013** [comment]
Fixed this issue as well as made the "All" button rounded on hover

![image](https://github.com/user-attachments/assets/695ec98f-b225-4af2-a445-f24f1190be40)
