### ISSUE TITLE
feature: Sidebar should show the various stages on the left

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#573]
![Screenshot 2024-08-26 at 10 15 08 PM](https://github.com/user-attachments/assets/d002c5f6-dfb1-4856-a8e1-c62ba323c2df)

**Comment by ItsFlash10** [comment]
On it, can you please assign this to me?

**Comment by keshav-exe** [comment]
@hkirat can you please elaborate a bit more regarding the stages?

**Comment by keshav-exe** [comment]
like bread crumbs?

**Comment by ItsFlash10** [comment]
@hkirat @devsargam added a [PR](#575 ) for this, please check and let me know if any changes are required.
<img width="1440" alt="Screenshot 2024-08-27 at 12 32 55 AM" src="https://github.com/user-attachments/assets/6a3e4a72-efd6-45c5-ae61-4bff87453646">

<img width="1440" alt="Screenshot 2024-08-27 at 12 33 05 AM" src="https://github.com/user-attachments/assets/93f00e21-d3b6-4a32-8b5b-8ee4d9c27027">
