### ISSUE TITLE
bug: Search Bar Not Displaying Result

### ISSUE THREAD

**Issue by kekubhai** [code100x/daily-code#574]
well typically the bug actually is this : 
![Screenshot 2024-08-26 225254](https://github.com/user-attachments/assets/7a63f06f-cc4b-46fe-83ea-f968e5bc13fd)

**Comment by IAmRiteshKoushik** [comment]
@kekubhai has this been resolved ? I don't see any updates/fixes on my end.

**Comment by kekubhai** [comment]
I saw the same issue being raised quite a few time
