### ISSUE TITLE
feature: add a search on the frontend

### ISSUE THREAD

**Issue by devsargam** [code100x/daily-code#576]
**Is your feature request related to a problem? Please describe.**
Currently, the search functionality is not working properly since the API key for search has expired.

**Describe the solution you'd like**
Just search the title of all the topics we are getting from the backend. Use [Fuse.js](https://www.fusejs.io/) to do some fuzzy search.

**Additional context**
Don't remove the elastic search logic just replace with fusejs as an interim solution

**Comment by ShubhamMewara** [comment]
@devsargam 
we already have the old search component `SearchDialog` I think we can just replace it with `ContentSearch` instead of adding
new search component and logic

**Comment by devsargam** [comment]
Do we have some sort of fuzzy search logic with it?

**Comment by Ashutoshpadhi629** [comment]
@devsargam ,  fuse.js should run on a client or we have to make a different server actions for it?
