### ISSUE TITLE
bug: Code highlighting gone after recent update

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#579]
![Screenshot 2024-08-27 at 11 37 23 AM](https://github.com/user-attachments/assets/ed04b825-3f5f-40ab-a19c-2e421800a197)

**Comment by ItsFlash10** [comment]
@hkirat I have fixed it here #575. Please check once :)

**Comment by devsargam** [comment]
Can confirm. Already resolved @hkirat

**Comment by devsargam** [comment]
![image](https://github.com/user-attachments/assets/f1ae9ad5-1ff1-40cd-a4dc-55e4e8188273)
