### ISSUE TITLE
Learning Paths Should be sorted according to Creation Date 

### ISSUE THREAD

**Issue by PranavKumar20** [code100x/daily-code#58]
Currently Learning Paths are displayed in random order on the website, But if is displayed in sorted to date it will be better to navigate.

**Comment by SujithThirumalaisamy** [comment]
`const tracks = await db.track.findMany({
      where: {
        hidden: false,
      },
      include: {
        problems: {
          select: {
            problem: true,
          },
          orderBy: [
            {
              sortingOrder: "desc",
            },
          ],
        },
        category: {
          select: {
            category: true,
          },
        },
      },
      orderBy: {
        createdAt: "asc",
      },
    });`
    
    It seems that the query is perfectly fine.
