### ISSUE TITLE
feature: Change dark mode background color for better readability

### ISSUE THREAD

**Issue by Ipshita02** [code100x/daily-code#583]
The current background color in dark mode is set to `bg-neutral-950`, which is a very dark shade. This can cause eye strain and reduce readability for users when reading for extended periods.

I propose changing the dark mode background color to a more reader-friendly shade, such as a dark gray (`#2D2D2D`) or navy blue (`#010B16`). These colors are easier on the eyes and enhance readability by reducing the harsh contrast between the background and text.

An alternative could be to allow users to customize the dark mode color themselves via a settings option. However, a default change to a more reader-friendly dark mode background would immediately benefit all users without requiring customization.

Here are some screenshots comparing the current dark mode background with the proposed new background colors:

*Current Dark Mode Background (`bg-neutral-950`):*

![Screenshot 2024-08-27 152440](https://github.com/user-attachments/assets/ed81f965-2c66-4ceb-a950-a6aefd6578d3)

*Suggested Dark Mode Background (Dark Gray):*

![Screenshot 2024-08-27 152441](https://github.com/user-attachments/assets/94c3a7b3-4181-4d18-9c01-9a819cb359ac)

*Suggested Dark Mode Background (Navy Blue):*

![Screenshot 2024-08-27 152442](https://github.com/user-attachments/assets/c08406bf-b1f3-4759-9b5b-50b1cc41e474)

Changing to a slightly lighter shade will improve readability and reduce eye strain, especially in low-light environments.

**I would like to work on this issue myself.**

**Comment by thecurioussailor** [comment]
@devsargam Please assign me this issue.

**Comment by devsargam** [comment]
Can have different varients of dark modes too

**Comment by Ipshita02** [comment]
> similar to how moneytype does it

Ok maybe we can have all three color options in the dark mode

**Comment by toufiqfarhan0** [comment]
> similar to how moneytype does it

can we use external library for this??

**Comment by ItsFlash10** [comment]
> Can have different varients of dark modes too

On it

**Comment by ItsFlash10** [comment]
#602 #603 will fix this

**Comment by Pandey-A** [comment]
@devsargam Please assign this to me . I would love to work on this
 Like the job is to make a theme like stuff where we can adjust the shades of the dark mode background colour .

**Comment by devsargam** [comment]
I agre @ItsFlash10 thank u sir. Closing
