### ISSUE TITLE
feature: Syntax Highlighting 

### ISSUE THREAD

**Issue by viralgupta** [code100x/daily-code#593]
**Is your feature request related to a problem? Please describe.**
We can improve readability by applying syntax highlighting, right now due to high contrast between background and text, it is a little straining on the eyes and difficult to read code.

eg:
![image](https://github.com/user-attachments/assets/b8132ab2-932c-458f-be65-12777cc35bda)

**Describe the solution you'd like**
We can use any available syntax highlighter in markdown parser like `react-markdown` support syntax highlighting.

**Comment by devsargam** [comment]
Already resolved but haven't been deployed
