### ISSUE TITLE
feature: Logout Dialog box for confirmation

### ISSUE THREAD

**Issue by BearerOP** [code100x/daily-code#594]
**Is your feature request related to a problem? Please describe.**
- Sometimes user misclick the logout button instead of something else due to which he needs to login again which creates a bad user experience.

**Describe the solution you'd like**
- When the user click on the logout button a Dialog box should appear to take confirmation consent for logging out.

**Additional context**

https://github.com/user-attachments/assets/f08538ce-084e-448d-94db-1aa2468f74f2

**Comment by devsargam** [comment]
@BearerOP I think whatever we have right now is fine. Else it will just complicate the workflow.

**Comment by BearerOP** [comment]
Okay the let’s keep it as is. We can tweak things later if needed. Thanks!

**Comment by BearerOP** [comment]
> @BearerOP I think whatever we have right now is fine. Else it will just complicate the workflow.

Okay the let’s keep it as is. We can tweak things later if needed. Thanks!

**Comment by devsargam** [comment]
Thanks @BearerOP. Love the enthusiasm but closing for now
