### ISSUE TITLE
Performance improvement - [Grey out Prev Button in First page lesson and Next Button in Last page of a lesson]

### ISSUE THREAD

**Issue by MadhaneeswaranP** [code100x/daily-code#60]
To enhance performance and prevent unnecessary API calls to the backend, we can implement the following improvements on the lesson page:

1. Disable Prev Button on First Slide:
When the user is on the first slide of the lesson, the Prev Button should be greyed out and disabled. This will visually indicate to the user that they cannot navigate to the previous slide since they are already on the first slide. Additionally, it prevents any accidental clicks that might trigger unnecessary API calls.

2. Disable Next Button on Last Slide:
Similarly, when the user reaches the last slide of the lesson, the Next Button should be greyed out and disabled. This informs the user that they have reached the end of the lesson and cannot proceed further. Disabling the Next Button also prevents any unnecessary API calls that might occur if the user attempts to navigate beyond the last slide.

![Daily_Code_Improvements](https://github.com/code100x/daily-code/assets/78028332/8f8a7dcc-9c1f-4c69-923a-12153d2fed7e)

CC: @hkirat

**Comment by MadhaneeswaranP** [comment]
I would like to work on this improvement.

**Comment by RitikBora** [comment]
@MadhaneeswaranP  hey sorry, I seem to have missed your comment. I'm happy to take back my PR if you wish to work on this.

Thanks,
Ritik

**Comment by MadhaneeswaranP** [comment]
@RitikBora No issues. Let it be there 😉 

Kindly mention to close this issue once your PR is merged.

**Comment by RitikBora** [comment]
@hkirat could you please have a look?
