### ISSUE TITLE
bug: Slides readability affected

### ISSUE THREAD

**Issue by Eshan-Sharma** [code100x/daily-code#600]
![image](https://github.com/user-attachments/assets/1c933f21-6ff9-4adf-b067-710f7667a0a2)

**Bug and Expected Behavior**
The slides content should be readable and the navigation buttons should be easily accessible. Currently the UI makes it difficult to read and access the buttons. 

**Suggestion**
Kindly add a button to view the classic or legacy version to revert back to the original version [If anyone does not want to keep up with the version updates]
 - Browser : Issue is persistent in all the browsers [Edge, Brave, Chrome]
 
- Kindly fix these issues -  https://pagespeed.web.dev/analysis/https-projects-100xdevs-com-tracks-sol-tokens-Programs--Accounts-and-the-Token-Program-3/m041wkebb1?form_factor=mobile

- Added Lighthouse metrics as well - https://lighthouse-metrics.com/lighthouse/checks/e1a8c5db-36aa-4a0c-a231-fa790448bdbd

**Comment by devsargam** [comment]
Done sir
