### ISSUE TITLE
bug: Category Buttons out of box

### ISSUE THREAD

**Issue by Vishawdeep-Singh** [code100x/daily-code#601]
**Describe the bug**
When you arrive at landing page you see at top that Cohort 3 Web3 and Cohort 3 Web dev out of box

**To Reproduce**
1. Go to https://projects.100xdevs.com/
2. See at top bar where different categories are

**Expected behavior**
Can implement right and left buttons which can do horizontal scrolling left and right by user's choice in case more categories can be added in the future

**Screenshots or GIFs**
<img width="1440" alt="Screenshot 2024-08-29 at 1 32 30 PM" src="https://github.com/user-attachments/assets/6727b52e-aa89-42ba-ac79-20812ab0f498">
.

**Info (please complete the following information):**
 - Browser [e.g. chrome]

**Additional context**

**Comment by toufiqfarhan0** [comment]
UI is changing. Until then wait

**Comment by Vishawdeep-Singh** [comment]
yeah man I figured when i cloned the repo

**Comment by rajatrar** [comment]
@Vishawdeep-Singh can you assign this to me I have some idea to fix it correctly.

**Comment by csgaikwad** [comment]
If no one is doing this can i do it ?
We can simply solve this issue by adding overflow-auto and create  a CSS class hideScrollbar to hide the scrollbar.

## It would look like this

![ScreenRecording2024-08-29225317-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/086f328d-7c14-466e-81a8-18a5491190f5)

**Comment by csgaikwad** [comment]
> Have you updated the branch of your repo??

I haven't started working on the issue yet. Are you asking if I need to create a new branch, or are you referring to the main branch? Could you please clarify?

**Comment by vverma022** [comment]
I'd like to work on the issue. It can be implemented by using 2 arrows which will control the scroll direction

**Comment by toufiqfarhan0** [comment]
> I'd like to work on the issue. It can be implemented by using 2 arrows which will control the scroll direction



> > Have you updated the branch of your repo??
> 
> I haven't started working on the issue yet. Are you asking if I need to create a new branch, or are you referring to the main branch? @toufiqfarhan0 Could you please clarify?

clone the repo and see the magic

**Comment by csgaikwad** [comment]
> Have you updated the branch of your repo??

i guess you are talking about Legacy UI, i hope they make it responsive

**Comment by toufiqfarhan0** [comment]
> > Have you updated the branch of your repo??
> 
> i guess you are talking about Legacy UI, i hope they make it responsive

yesss

**Comment by devsargam** [comment]
This is already fixed
