### ISSUE TITLE
UI Enhancement: Learning Paths Navigation Menu

### ISSUE THREAD

**Issue by KISHANsingh0001** [code100x/daily-code#617]
The alignment of the Learning Paths navigation menu needs improvement, especially for categories with longer names. Please review and adjust the layout for better spacing and readability.

Screenshot:
![image](https://github.com/user-attachments/assets/61c7ce0c-4438-48de-a314-06efed23527d)

**Comment by toufiqfarhan0** [comment]
wait until latest deployment is done

**Comment by KISHANsingh0001** [comment]
ok
