### ISSUE TITLE
bug: Build is failing

### ISSUE THREAD

**Issue by devsargam** [code100x/daily-code#625]
### Steps to reproduce
- Setup the repo
- Put all the environment variables
- Run `yarn build`

The build is not successful

**Comment by ItsFlash10** [comment]
@devsargam it worked after running `yarn upgrade`

![Screenshot 2024-09-10 at 5 39 15 PM](https://github.com/user-attachments/assets/7fe59cd5-d5c2-446b-9745-d26772bfe5cb)

**Comment by devsargam** [comment]
Testing

**Comment by devsargam** [comment]
Thank u sir @ItsFlash10. New saviour in the town

**Comment by ItsFlash10** [comment]
> Thank u sir @ItsFlash10. New saviour in the town

Infinite sum game xD
