### ISSUE TITLE
bug: Failing to install dependecies at setup

### ISSUE THREAD

**Issue by Zafeeruddin** [code100x/daily-code#632]
**Describe the bug**
I tried setting up repository locally by `docker compose watch` and it shows and at 4th step it fails to install dependencies where required.

Error: ` => => # info There appears to be trouble with your network connection. Retrying...`

I increased the network timeout
`yarn install --network-timeout=300000`

Still faced the same issue
![image](https://github.com/user-attachments/assets/81a004bd-344d-479a-bc45-400df1360ecb)

**To Reproduce**
1. Clone repo
2. `docker compose watch`

**Comment by devsargam** [comment]
This is your internet problem. I have got it running on my end

**Comment by Zafeeruddin** [comment]
![image](https://github.com/user-attachments/assets/96da5334-5f2b-4972-a8f7-cb7a29c6ebee)
Internet is fine for  me
Tried switching to different networks

**Comment by Zafeeruddin** [comment]
Removing config settings worked for me 

yarn config delete https-proxy
yarn config delete proxy

Thanks Sir 

Btw why is new UI disabled? or is it just not reflecting for me?
![image](https://github.com/user-attachments/assets/42f8454a-e56a-4ba2-bbff-7e3c1572353b)
