### ISSUE TITLE
feature: Enforce DCO Sign-Off for Commits

### ISSUE THREAD

**Issue by sudhanshutech** [code100x/daily-code#642]
## The Problem/Issue:
Currently, the project does not enforce or provide guidance on the Developer Certificate of Origin (DCO) sign-off process for commits. This can result in commits without proper legal acknowledgment from contributors, which may lead to issues in managing contributor agreements and tracking the contributors who made the commits.

## Solution proposed
I propose implementing a DCO check as part of the project's contribution guidelines and CI pipeline to ensure that all commits are signed off by the authors. This can be done using a DCO verification bot (like the DCO GitHub app) that automatically checks whether the Signed-off-by line is present in every commit message. Additionally, update the project's contribution documentation to include instructions on how contributors can sign off their commits using the --signoff option when making commits.

**Additional context**

- The DCO ensures that contributors acknowledge they have the right to submit their work under the project's open-source license.

Here’s an example of a Signed-off-by line that should be included in commit messages:

```powershell
Signed-off-by: Full Name <email@example.com>
``` 

- The DCO GitHub app can be easily integrated into the project's CI/CD to automate this process. https://github.com/apps/dco
- Either the signing can be set directly to vs code or any editors used and we can just then directly commit or we can run `git commit -s -m "<the commit message>"`

**Comment by sudhanshutech** [comment]
I will be happy to work on this.

Thank you

**Comment by devsargam** [comment]
This is unnecessary for us at this point. Most of the contributors are new to oss so this will just create difficulties there
