### ISSUE TITLE
UX Improvement : Navigation to next or previous page can be on the bottom of the page.

### ISSUE THREAD

**Issue by rrrrratul** [code100x/daily-code#65]
Scrolling through the contents of slides, the cursor rests mostly on the bottom right side of the screen, it could be helpful if navigation to previous and next slides are available as an icon on the bottom right of each slide.

**Comment by siddanth-6365** [comment]
i guess there is no use of this feature since we have navbar sticky which has next,prev buttons for big screens and for mobile view there is on scroll up navbar visible

**Comment by Avinaba-Mazumdar** [comment]
Hii, do we want it to look like this on mobile screens?
![image](https://github.com/code100x/daily-code/assets/53753281/2922dfe8-45c2-44a1-bd64-c12b85b21c8a)

**Comment by Aayuslad** [comment]
what if the user needs to move to the previous or next chapter in the middle of a page? It would be more user-friendly to keep those buttons on the navbar. we can implement this while still maintaining those buttons in the navbar.
