### ISSUE TITLE
bug: Pagination Section Cursor Issue

### ISSUE THREAD

**Issue by amartripathi0** [code100x/daily-code#654]
**Description**
The pagination section is currently displaying a default cursor on hover instead of a pointer cursor, which can lead to confusion regarding the interactivity of the buttons.

**Steps to reproduce**
1. Navigate to the landing page.
2. Scroll to the bottom of the page to locate the Pagination Section.
3. Hover over the "Prev," "Next," and other page buttons.
4. Observe that the cursor remains as a default arrow instead of changing to a pointer.

**Current Behaviour** (Default cusor on hover)
The cursor does not change on hover, indicating that the buttons are not interactive.
![Screenshot from 2024-09-19 13-55-47](https://github.com/user-attachments/assets/b2571548-86c2-4cd9-9010-5b2d73b2b765)

**Expected Behaviour** 
The cursor should change to a pointer when hovering over pagination buttons, indicating that they are clickable.
![Screenshot from 2024-09-19 13-56-05](https://github.com/user-attachments/assets/148d989c-2372-4157-8ea3-47b0f3e38bf3)

**Solution**
Adding `cursor-pointer` class to `<PaginationItem/> in LandingScreen`

**Comment by jals413** [comment]
But, the pagination does not work on clicking those buttons, also all the tracks are loaded with scroll, thus pagination is not required

Either one of the should be implemented 

https://github.com/code100x/daily-code/issues/651

**Comment by devsargam** [comment]
@jals413 I agree. I will think about it and comeup with something

**Comment by jals413** [comment]
https://github.com/code100x/daily-code/pull/652 

I have created a PR for removing pagination as it does not make any sense here, if you feel so you can merge it.

**Comment by devsargam** [comment]
Yeah saw that @jals413

**Comment by amartripathi0** [comment]
@jals413  @devsargam  we need to scroll alot to reach the end of the landing page and I guess its not a good UX and idea to display all the tracks as in the future the no. of tracks gonna increase only.

**Comment by jals413** [comment]
I agree, but in my opinion if you want to handle pagination it should be handled from BE then only it will make the true sense

**Comment by amartripathi0** [comment]
yes, that's the optimial way to avoid overfetching
