### ISSUE TITLE
bug: Missing Images project cards

### ISSUE THREAD

**Issue by Prathamesh-Chavan-232** [code100x/daily-code#682]
**Describe the bug**
Images are missing in the project track cards 

**To Reproduce**
1. Scroll down to projects section in the landing page

**Expected behavior**
Cards should display the respective images.

**Screenshots or GIFs**
<img width="847" alt="Screenshot 2024-10-08 at 2 27 44 PM" src="https://github.com/user-attachments/assets/8dd48590-e9ca-49b2-b22d-700f6fc8a020">

**Info (please complete the following information):**
 - Chrome
 - 129.0.6668.90

**Comment by EzMav3ick** [comment]
works fine in my chrome browser
just loads a little late

**Comment by kataltarun** [comment]
som1 mark it solved !!
