### ISSUE TITLE
feature: Allow a way to embed canva slides to the platform

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#694]
Some slides are canva slides
For eg - https://www.canva.com/design/DAGVOvVE1ow/wTKvuP2OnyLuvr4aAwtM-A/edit?utm_content=DAGVOvVE1ow&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

We need to allow admins to upload this link and it should unfurl as slides on the platform

**Comment by Jatin24062005** [comment]
@hkirat i m begginer i just wanted to know you need that slides in your video description directly or something else   feature ??

**Comment by saurabhraghuvanshii** [comment]
@hkirat assign/

**Comment by ItsFlash10** [comment]
@hkirat - #695: UI might not be the best but does the job ig xD


https://github.com/user-attachments/assets/5cd6c567-8910-48d2-9d3c-8cf5eef8ba66
