### ISSUE TITLE
bug: Submission route is not working

### ISSUE THREAD

**Issue by Shu12388y** [code100x/daily-code#697]
**Describe the bug**
In the profile section, there is a submission tab that is not working.

**Expected behavior**
There should be a submission page and users can submit content or report bugs

**Screenshots or GIFs**

![Screenshot (51)](https://github.com/user-attachments/assets/21fa108a-bced-4023-99ac-b394d1540d07)

![Screenshot (52)](https://github.com/user-attachments/assets/d6daf0c9-9619-42e8-b6a9-d8ddb4a0d261)

**Info (please complete the following information):**

@hkirat can you assign this issue to me or I can add new feature to it

**Comment by rishabdev2997** [comment]
Hi @hkirat, @Shu12388y  mentioned that the submission route isn't working. Could it be that the submission page hasn’t been built yet? Please correct me if I’m mistaken!

**Comment by Shu12388y** [comment]
@rishabdev2997 yes the submission page is not created yet

**Comment by devsargam** [comment]
There's no need to submission route. We have a separate project algo arena
