### ISSUE TITLE
Add MCQ based questions type

### ISSUE THREAD

**Issue by hkirat** [code100x/daily-code#73]
Right now we have `code` and `blog` type
We need a simple `MCQ question type which'll have a blog on the left, and question on the right that'll help the user revise the topic
1. Needs to have a new backend collection for `MCQ` questions (doesnt need to normalize can have everything in the same doc)
2. Need a new `submissions` collection that stores the users submissions
3. Frontend needs some sort of confetti when the user selects the right option

**Comment by g4ze** [comment]
Hey @hkirat /any-maintainer, can I take up this issue?

**Comment by utnim2** [comment]
working on it

**Comment by hkirat** [comment]
go for it its open

**Comment by Programmer-Dost** [comment]
There is no node backend and no directories such as code and blog. Where should I create the backend db collection?
