### ISSUE TITLE
List item taking excess width than required (higher screen res)

### ISSUE THREAD

**Issue by Karan4299** [code100x/daily-code#84]
## Description
On main project page, where all slides are present. On higher screen res the gap between column increases, but we are also able to click on blank space to select the slide in line (ss attached)

<img width="1512" alt="Screenshot 2024-03-17 at 2 52 40 AM" src="https://github.com/code100x/daily-code/assets/83075612/d4ab954b-60a6-4e0a-879d-dad3600adfbc">

### current behaviour:
Getting pointer cursor even outside the list item (in between column gap, specially when width increases)

### Expected behaviour:
Should not able to open the slide if cursor is outside it. And list items should align horizontally centre on higher widths.

### Steps to Reproduce:
>  - Go to https://projects.100xdevs.com/
>  - Press Ctrl/Cmd + '-' to increase the width/resolution.
>  - Hover between column gap (outside list item.) You will be able to select item and get pointer icon.

### Environment:
prod

**Comment by Karan4299** [comment]
minor css issue. I already have a fix ready. Can I take this

**Comment by hkirat** [comment]
looks great, can u PR it?

**Comment by mayankgb** [comment]
@hkirat can u please this pull request
