### ISSUE TITLE
[BUG] : Download button is not working properly.

### ISSUE THREAD

**Issue by pkmanas22** [code100x/daily-code#93]
**When click on Download it will navigate into another tab and content is generated but there is error in generating pdf** 

![image](https://github.com/code100x/daily-code/assets/125083715/092f320c-f3a9-46af-8cef-0337889c823c)
<br>
![image](https://github.com/code100x/daily-code/assets/125083715/e72ff140-437e-4543-9c9d-855647452710)

**Comment by devsargam** [comment]
Hopefully, fixed in #88

**Comment by pkmanas22** [comment]
Still issue persists

**Comment by pkmanas22** [comment]
> Hopefully, fixed in #88

Still issue persists

**Comment by devsargam** [comment]
hey @hkirat have u pushed the updated code?
Also get well soon veere
